/**
 * GENERATED by scripts/port-content.mjs from old/js/data.js. Do not edit by hand.
 *
 * This is the authored training programme, ported verbatim. The source file's own
 * header says it plainly: do not "improve" these. Rep ranges, loads, RPE targets and
 * every line of bilingual technique text are the user's training plan, not copy.
 */

import type { Block, Prescription, ProgKind, SlotPrescriptions } from './schema';

export const BLOCKS: readonly Block[] = [
  {
    "k": "b1",
    "t": {
      "pt": "Bloco 1",
      "en": "Block 1"
    },
    "s": {
      "pt": "Volume · Sem 1-4",
      "en": "Volume · Wk 1-4"
    }
  },
  {
    "k": "b2",
    "t": {
      "pt": "Bloco 2",
      "en": "Block 2"
    },
    "s": {
      "pt": "Intensidade · Sem 5-8",
      "en": "Intensity · Wk 5-8"
    }
  },
  {
    "k": "b3",
    "t": {
      "pt": "Bloco 3",
      "en": "Block 3"
    },
    "s": {
      "pt": "Pesado · Sem 9-11",
      "en": "Heavy · Wk 9-11"
    }
  },
  {
    "k": "dl",
    "t": {
      "pt": "Deload",
      "en": "Deload"
    },
    "s": {
      "pt": "Descarga · Sem 12",
      "en": "Unload · Wk 12"
    }
  }
];

/**
 * The author's periodization generator, carried across unchanged. One call yields
 * all four block prescriptions for a slot, which is why the day tables stay legible.
 */
const RANGES: Record<ProgKind, Record<'b1' | 'b2' | 'b3' | 'dl', readonly [string, string]>> = {
  "comp": {
    "b1": [
      "10-12",
      "7-8"
    ],
    "b2": [
      "8-10",
      "8"
    ],
    "b3": [
      "6-8",
      "8-9"
    ],
    "dl": [
      "8-10",
      "5-6"
    ]
  },
  "acc": {
    "b1": [
      "12-15",
      "7-8"
    ],
    "b2": [
      "10-12",
      "8"
    ],
    "b3": [
      "8-10",
      "8-9"
    ],
    "dl": [
      "12",
      "5-6"
    ]
  },
  "iso": {
    "b1": [
      "15",
      "8"
    ],
    "b2": [
      "12-15",
      "8"
    ],
    "b3": [
      "10-12",
      "8-9"
    ],
    "dl": [
      "12",
      "5-6"
    ]
  },
  "core": {
    "b1": [
      "30-45s",
      "—"
    ],
    "b2": [
      "45-60s",
      "—"
    ],
    "b3": [
      "45-60s",
      "—"
    ],
    "dl": [
      "30s",
      "—"
    ]
  }
};

export function prog(
  sets: number,
  loadB1: string,
  rest: string,
  kind: ProgKind,
): SlotPrescriptions {
  const R = RANGES[kind];
  const s3 = kind === 'comp' ? sets + 1 : sets;
  const at = (k: 'b1' | 'b2' | 'b3' | 'dl', s: number, l: string): Prescription => ({
    s,
    r: R[k][0],
    rpe: R[k][1],
    l,
    rest,
  });
  return {
    b1: at('b1', sets, loadB1),
    b2: at('b2', sets, 'base + carga'),
    b3: at('b3', s3, 'pesada'),
    dl: at('dl', Math.max(2, sets - 1), 'carga B2'),
  };
}
