/**
 * Os quatro blocos da periodização, nas quatro línguas.
 *
 * O cabeçalho dizia "GENERATED by scripts/port-content.mjs" e deixou de ser verdade a
 * 2026-09-21. Não se corre `npm run port:content` por cima deste ficheiro.
 *
 * `t` guarda o nome velho ("Bloco 1"). Desde a fase 001 os ecrãs **não o mostram** —
 * leem `t.phase[k]` do dicionário, que diz o que a fase é e não o número dela. Fica
 * aqui porque a chave ainda é a chave, e traduzido porque um campo meio traduzido é
 * uma armadilha para quem o voltar a ligar.
 *
 * `s` é o que aparece no ecrã: a faixa de semanas. "Sem" é a abreviatura de semana, e
 * cada língua abrevia à sua — "Wk", "Sem", "Sem." — porque o rótulo vive numa banda
 * estreita da jornada.
 */

import type { Block, Localized, Prescription, ProgKind, SlotPrescriptions } from './schema';

export const BLOCKS: readonly Block[] = [
  {
    "k": "b1",
    "t": {
      "pt": "Bloco 1",
      "en": "Block 1",
      "es": "Bloque 1",
      "fr": "Bloc 1"
    },
    "s": {
      "pt": "Volume · Sem 1-4",
      "en": "Volume · Wk 1-4",
      "es": "Volumen · Sem 1-4",
      "fr": "Volume · Sem. 1-4"
    }
  },
  {
    "k": "b2",
    "t": {
      "pt": "Bloco 2",
      "en": "Block 2",
      "es": "Bloque 2",
      "fr": "Bloc 2"
    },
    "s": {
      "pt": "Intensidade · Sem 5-8",
      "en": "Intensity · Wk 5-8",
      "es": "Intensidad · Sem 5-8",
      "fr": "Intensité · Sem. 5-8"
    }
  },
  {
    "k": "b3",
    "t": {
      "pt": "Bloco 3",
      "en": "Block 3",
      "es": "Bloque 3",
      "fr": "Bloc 3"
    },
    "s": {
      "pt": "Pesado · Sem 9-11",
      "en": "Heavy · Wk 9-11",
      "es": "Pesado · Sem 9-11",
      "fr": "Lourd · Sem. 9-11"
    }
  },
  {
    "k": "dl",
    "t": {
      "pt": "Deload",
      "en": "Deload",
      "es": "Deload",
      "fr": "Deload"
    },
    "s": {
      "pt": "Descarga · Sem 12",
      "en": "Unload · Wk 12",
      "es": "Descarga · Sem 12",
      "fr": "Décharge · Sem. 12"
    }
  }
];

/**
 * The author's periodization generator, carried across unchanged. One call yields
 * all four block prescriptions for a slot, which is why the day tables stay legible.
 */
const RANGES: Record<ProgKind, Record<'b1' | 'b2' | 'b3' | 'dl', readonly [string, string]>> = {
  "comp": {
    "b1": [
      "10-12",
      "7-8"
    ],
    "b2": [
      "8-10",
      "8"
    ],
    "b3": [
      "6-8",
      "8-9"
    ],
    "dl": [
      "8-10",
      "5-6"
    ]
  },
  "acc": {
    "b1": [
      "12-15",
      "7-8"
    ],
    "b2": [
      "10-12",
      "8"
    ],
    "b3": [
      "8-10",
      "8-9"
    ],
    "dl": [
      "12",
      "5-6"
    ]
  },
  "iso": {
    "b1": [
      "15",
      "8"
    ],
    "b2": [
      "12-15",
      "8"
    ],
    "b3": [
      "10-12",
      "8-9"
    ],
    "dl": [
      "12",
      "5-6"
    ]
  },
  "core": {
    "b1": [
      "30-45s",
      "—"
    ],
    "b2": [
      "45-60s",
      "—"
    ],
    "b3": [
      "45-60s",
      "—"
    ],
    "dl": [
      "30s",
      "—"
    ]
  }
};

/**
 * The three loads `prog()` writes itself, in all four languages.
 *
 * These are not numbers — they are sentences about the number: "whatever you lifted
 * in block 1, plus some", "heavy", "back to the block 2 load". They appeared in the
 * Carga column of every screen in Portuguese whatever language the app was in, which
 * is the day-name bug one column to the right. Named here rather than written inline
 * so there is one place to read what block 2 actually asks of you.
 */
const B2_LOAD: Localized = {
  pt: 'base + carga',
  en: 'base + load',
  es: 'base + carga',
  fr: 'base + charge',
};

const B3_LOAD: Localized = { pt: 'pesada', en: 'heavy', es: 'pesada', fr: 'lourde' };

const DL_LOAD: Localized = { pt: 'carga B2', en: 'B2 load', es: 'carga B2', fr: 'charge B2' };

export function prog(
  sets: number,
  loadB1: Localized,
  rest: string,
  kind: ProgKind,
): SlotPrescriptions {
  const R = RANGES[kind];
  const s3 = kind === 'comp' ? sets + 1 : sets;
  const at = (k: 'b1' | 'b2' | 'b3' | 'dl', s: number, l: Localized): Prescription => ({
    s,
    r: R[k][0],
    rpe: R[k][1],
    l,
    rest,
  });
  return {
    b1: at('b1', sets, loadB1),
    b2: at('b2', sets, B2_LOAD),
    b3: at('b3', s3, B3_LOAD),
    dl: at('dl', Math.max(2, sets - 1), DL_LOAD),
  };
}
