/**
 * As duas máquinas de cardio, nas quatro línguas.
 *
 * O cabeçalho dizia "GENERATED by scripts/port-content.mjs" e deixou de ser verdade a
 * 2026-09-21. Não se corre `npm run port:content` por cima deste ficheiro.
 *
 * `nPT`/`nEN` passaram a `n` no Passo F: dois campos não seguram quatro línguas.
 * `dur` fica como está — "20–25 min" lê-se igual nas quatro, e o traço é um en-dash
 * a sério, não um hífen.
 */

import type { CardioEntry } from './schema';

export const CARDIO: Readonly<Record<string, CardioEntry>> = {
  "treadmill": {
    "n": {
      "pt": "Passadeira",
      "en": "Treadmill",
      "es": "Cinta de correr",
      "fr": "Tapis de course"
    },
    "anim": "run",
    "dur": "20–25 min",
    "intens": {
      "pt": "Moderada — Zona 2, dá para conversar",
      "en": "Moderate — Zone 2, you can still talk",
      "es": "Moderada — Zona 2, puedes hablar",
      "fr": "Modérée — Zone 2, tu peux encore parler"
    },
    "obj": {
      "pt": "Queima de gordura sem stress articular; baixo impacto para as costas.",
      "en": "Fat burning without joint stress; low impact on the back.",
      "es": "Quema de grasa sin estrés articular; bajo impacto para la espalda.",
      "fr": "Brûler des graisses sans stress articulaire ; faible impact sur le dos."
    },
    "tips": {
      "pt": [
        "Inclinação 3–6% e ritmo de caminhada rápida poupa os joelhos.",
        "Postura direita, sem te agarrares aos apoios."
      ],
      "en": [
        "A 3–6% incline at a brisk walking pace spares the knees.",
        "Stand tall — do not hang on to the handles."
      ],
      "es": [
        "Una inclinación del 3–6% a ritmo de marcha rápida cuida las rodillas.",
        "Mantén la postura erguida, sin agarrarte a los apoyos."
      ],
      "fr": [
        "Une inclinaison de 3–6 % à allure de marche rapide ménage les genoux.",
        "Tiens-toi droit, sans t'accrocher aux poignées."
      ]
    }
  },
  "bike": {
    "n": {
      "pt": "Bicicleta",
      "en": "Stationary Bike",
      "es": "Bicicleta estática",
      "fr": "Vélo d'appartement"
    },
    "anim": "bike",
    "dur": "15–20 min",
    "intens": {
      "pt": "Moderada — respiração elevada mas controlada",
      "en": "Moderate — breathing up but under control",
      "es": "Moderada — respiración alta pero controlada",
      "fr": "Modérée — respiration haute mais maîtrisée"
    },
    "obj": {
      "pt": "Cardio de baixo impacto, alternativa ou complemento à passadeira.",
      "en": "Low-impact cardio, an alternative or complement to the treadmill.",
      "es": "Cardio de bajo impacto, alternativa o complemento a la cinta.",
      "fr": "Cardio à faible impact, en alternative ou en complément du tapis."
    },
    "tips": {
      "pt": [
        "Ajusta o selim: joelho quase esticado no fundo da pedalada.",
        "Costas neutras; evita curvar demasiado a lombar."
      ],
      "en": [
        "Set the saddle so the knee is almost straight at the bottom of the stroke.",
        "Neutral back; avoid rounding the lower back."
      ],
      "es": [
        "Ajusta el sillín: la rodilla casi estirada al final del pedaleo.",
        "Espalda neutra; evita curvar demasiado la zona lumbar."
      ],
      "fr": [
        "Règle la selle : le genou presque tendu en bas du coup de pédale.",
        "Dos neutre ; évite de trop arrondir les lombaires."
      ]
    }
  }
};
