/**
 * GENERATED by scripts/port-content.mjs from old/js/data.js. Do not edit by hand.
 *
 * This is the authored training programme, ported verbatim. The source file's own
 * header says it plainly: do not "improve" these. Rep ranges, loads, RPE targets and
 * every line of bilingual technique text are the user's training plan, not copy.
 */

import type { CardioEntry } from './schema';

export const CARDIO: Readonly<Record<string, CardioEntry>> = {
  "treadmill": {
    "nPT": "Passadeira",
    "nEN": "Treadmill",
    "anim": "run",
    "dur": "20–25 min",
    "intens": {
      "pt": "Moderada — Zona 2, dá para conversar",
      "en": "Moderate — Zone 2, you can still talk"
    },
    "obj": {
      "pt": "Queima de gordura sem stress articular; baixo impacto para as costas.",
      "en": "Fat burning without joint stress; low impact on the back."
    },
    "tips": {
      "pt": [
        "Inclinação 3–6% e ritmo de caminhada rápida poupa os joelhos.",
        "Postura direita, sem te agarrares aos apoios."
      ],
      "en": [
        "A 3–6% incline at a brisk walking pace spares the knees.",
        "Stand tall — do not hang on to the handles."
      ]
    }
  },
  "bike": {
    "nPT": "Bicicleta",
    "nEN": "Stationary Bike",
    "anim": "bike",
    "dur": "15–20 min",
    "intens": {
      "pt": "Moderada — respiração elevada mas controlada",
      "en": "Moderate — breathing up but under control"
    },
    "obj": {
      "pt": "Cardio de baixo impacto, alternativa ou complemento à passadeira.",
      "en": "Low-impact cardio, an alternative or complement to the treadmill."
    },
    "tips": {
      "pt": [
        "Ajusta o selim: joelho quase esticado no fundo da pedalada.",
        "Costas neutras; evita curvar demasiado a lombar."
      ],
      "en": [
        "Set the saddle so the knee is almost straight at the bottom of the stroke.",
        "Neutral back; avoid rounding the lower back."
      ]
    }
  }
};
