/**
 * GENERATED by scripts/port-content.mjs from old/js/data.js. Do not edit by hand.
 *
 * This is the authored training programme, ported verbatim. The source file's own
 * header says it plainly: do not "improve" these. Rep ranges, loads, RPE targets and
 * every line of bilingual technique text are the user's training plan, not copy.
 */

import { prog } from './blocks';
import type { Day, DayItem, LocalizedText, SlotPrescriptions } from './schema';

const I = (ex: string, slots: SlotPrescriptions, note?: LocalizedText): DayItem => ({
  ex,
  ...slots,
  ...(note ? { note } : {}),
});

export const DAYS: readonly Day[] = [
  {
    "id": 1,
    "wd": {
      "pt": "Seg",
      "en": "Mon"
    },
    "ic": "",
    "theme": "q",
    "name": {
      "pt": "Perna — Quadríceps",
      "en": "Legs — Quads"
    },
    "short": {
      "pt": "Perna",
      "en": "Legs"
    },
    "eyebrow": {
      "pt": "Dia 1 · Inferior",
      "en": "Day 1 · Lower"
    },
    "mus": {
      "pt": [
        "Quadríceps",
        "Glúteo",
        "Panturrilha",
        "Core"
      ],
      "en": [
        "Quads",
        "Glutes",
        "Calves",
        "Core"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min bike + 1–2 séries de aproximação no Leg Press. Mobilidade de anca e joelho.",
      "en": "6–8 min bike + 1–2 ramp-up sets on the Leg Press. Hip and knee mobility."
    },
    "goal": {
      "pt": "Foco principal em quadríceps. Complementares (panturrilha e core) que não prejudicam a recuperação para a sexta (posterior).",
      "en": "Main focus on quads. Accessories (calves and core) that do not compromise recovery for Friday (hamstrings)."
    },
    "items": [
    I("legpress", prog(4, "60 kg cal", "2–3 min", "comp")),
    I("hack", prog(3, "— preencher", "2 min", "comp"), {
        "pt": "Alternativa: Agachamento Goblet se não houver máquina Hack.",
        "en": "Alternative: Goblet Squat if there is no Hack machine."
      }),
    I("legext", prog(3, "25 kg cal", "60–90 s", "iso")),
    I("lunge", prog(3, "10 kg/mão cal", "90 s", "acc")),
    I("calf_s", prog(4, "40 kg cal", "45–60 s", "iso")),
    I("plank", prog(3, "peso corporal", "45 s", "core")),
    ],
  },
  {
    "id": 2,
    "wd": {
      "pt": "Ter",
      "en": "Tue"
    },
    "ic": "",
    "theme": "push",
    "name": {
      "pt": "Tríceps",
      "en": "Triceps"
    },
    "short": {
      "pt": "Tríceps",
      "en": "Triceps"
    },
    "eyebrow": {
      "pt": "Dia 2 · Push",
      "en": "Day 2 · Push"
    },
    "mus": {
      "pt": [
        "Tríceps"
      ],
      "en": [
        "Triceps"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min elíptica/remo leve + rotações de ombro + 2 séries de aproximação no supino fechado. Aquece bem os cotovelos antes das extensões.",
      "en": "6–8 min easy elliptical/rower + shoulder rotations + 2 ramp-up sets on the close-grip bench. Warm the elbows well before the extensions."
    },
    "goal": {
      "pt": "Dia dedicado ao tríceps. Composto pesado primeiro, depois o trabalho acima da cabeça enquanto estás fresco — é a posição que mais faz crescer a cabeça longa — e os isolamentos só no fim.",
      "en": "Triceps-only day. Heavy compound first, then the overhead work while you are fresh — that position grows the long head most — and the isolation work last."
    },
    "items": [
    I("cgbench", prog(4, "— preencher", "2–3 min", "comp")),
    I("ohext", prog(4, "— preencher", "90 s", "acc"), {
        "pt": "Prioridade do dia: acima da cabeça alonga a cabeça longa, e é aí que ela mais cresce.",
        "en": "Priority of the day: overhead lengthens the long head, and that is where it grows most."
      }),
    I("dip", prog(3, "peso corporal", "2 min", "comp"), {
        "pt": "Tronco vertical — inclinar à frente passa o trabalho para o peito. Sem o peso do corpo ainda, usa a máquina assistida.",
        "en": "Stay upright — leaning forward shifts the work to the chest. Not there with bodyweight yet? Use the assisted machine."
      }),
    I("skull", prog(3, "— preencher", "60–90 s", "acc")),
    I("pushdown", prog(3, "20 kg cal", "60–90 s", "acc")),
    I("kickback", prog(2, "— preencher", "45–60 s", "iso"), {
        "pt": "Finalizador leve — aperta 1s no fim de cada repetição.",
        "en": "Light finisher — hold the squeeze for 1s on every rep."
      }),
    ],
  },
  {
    "id": 3,
    "wd": {
      "pt": "Qua",
      "en": "Wed"
    },
    "ic": "",
    "theme": "sh",
    "name": {
      "pt": "Ombro + Bíceps",
      "en": "Shoulders + Biceps"
    },
    "short": {
      "pt": "Ombro",
      "en": "Shoulders"
    },
    "eyebrow": {
      "pt": "Dia 3 · Push/Pull",
      "en": "Day 3 · Push/Pull"
    },
    "mus": {
      "pt": [
        "Deltoides",
        "Bíceps",
        "Trapézio"
      ],
      "en": [
        "Delts",
        "Biceps",
        "Traps"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min bike + Face Pull leve + rotações de ombro para aquecer a articulação.",
      "en": "6–8 min bike + light Face Pulls + shoulder rotations to warm the joint."
    },
    "goal": {
      "pt": "Desenvolvimento de ombro, elevações e trabalho de bíceps.",
      "en": "Shoulder pressing, raises and biceps work."
    },
    "items": [
    I("dbohp", prog(4, "10 kg/mão cal", "2–3 min", "comp")),
    I("lateral", prog(4, "6 kg/mão cal", "45–60 s", "iso")),
    I("reardelt", prog(3, "— preencher", "60 s", "acc")),
    I("dbcurl", prog(3, "10 kg/mão cal", "60–90 s", "acc")),
    I("hammer", prog(3, "10 kg/mão cal", "60–90 s", "acc")),
    I("cablecurl", prog(2, "— preencher", "60 s", "acc"), {
        "pt": "Finalizador de bíceps com tensão constante.",
        "en": "Biceps finisher with constant tension."
      }),
    ],
  },
  {
    "id": 4,
    "wd": {
      "pt": "Qui",
      "en": "Thu"
    },
    "ic": "",
    "theme": "back",
    "name": {
      "pt": "Costas + Peito",
      "en": "Back + Chest"
    },
    "short": {
      "pt": "Costas",
      "en": "Back"
    },
    "eyebrow": {
      "pt": "Dia 4 · Pull/Push",
      "en": "Day 4 · Pull/Push"
    },
    "mus": {
      "pt": [
        "Dorsal",
        "Costas sup.",
        "Peitoral",
        "Deltoide post."
      ],
      "en": [
        "Lats",
        "Upper back",
        "Chest",
        "Rear delt"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min remo/elíptica + Face Pull + aproximação na puxada e no supino.",
      "en": "6–8 min rower/elliptical + Face Pulls + ramp-up sets on the pulldown and the bench."
    },
    "goal": {
      "pt": "Costas e peito, os dois com volume a sério — o peito deixou de ser manutenção. Veio da terça, que passou a ser só tríceps.",
      "en": "Back and chest, both with real volume — the chest work is no longer maintenance. It moved here from Tuesday, which is now triceps only."
    },
    "items": [
    I("pulldown", prog(4, "40 kg cal", "2–3 min", "comp")),
    I("csrow", prog(3, "30 kg cal", "2 min", "comp")),
    I("seatedrow", prog(3, "35 kg cal", "90 s", "comp")),
    I("strarm", prog(3, "— preencher", "60–90 s", "acc")),
    I("facepull", prog(3, "15 kg cal", "60 s", "acc")),
    I("dbbench", prog(4, "14 kg/mão cal", "2–3 min", "comp")),
    I("incldb", prog(3, "12 kg/mão cal", "2 min", "comp")),
    I("pecdeck", prog(3, "25 kg cal", "60–90 s", "iso")),
    ],
  },
  {
    "id": 5,
    "wd": {
      "pt": "Sex",
      "en": "Fri"
    },
    "ic": "",
    "theme": "post",
    "name": {
      "pt": "Perna — Posterior + Panturrilha",
      "en": "Legs — Hamstrings + Calves"
    },
    "short": {
      "pt": "Perna",
      "en": "Legs"
    },
    "eyebrow": {
      "pt": "Dia 5 · Inferior",
      "en": "Day 5 · Lower"
    },
    "mus": {
      "pt": [
        "Posteriores",
        "Glúteo",
        "Panturrilha",
        "Core"
      ],
      "en": [
        "Hamstrings",
        "Glutes",
        "Calves",
        "Core"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min bike + mobilidade de anca + aproximação leve na elevação pélvica.",
      "en": "6–8 min bike + hip mobility + light ramp-up sets on the hip thrust."
    },
    "goal": {
      "pt": "Cadeia posterior (posteriores + glúteos) + panturrilha e complementares. SEM duplicar segunda (quadríceps).",
      "en": "Posterior chain (hamstrings + glutes) plus calves and accessories. No overlap with Monday (quads)."
    },
    "items": [
    I("hipthrust", prog(4, "40 kg cal", "2–3 min", "comp")),
    I("dbrdl", {
        "b1": {
          "s": 3,
          "r": "8-10",
          "rpe": "6-7",
          "l": "12 kg/mão cal",
          "rest": "2 min"
        },
        "b2": {
          "s": 3,
          "r": "8-10",
          "rpe": "7",
          "l": "base + carga",
          "rest": "2 min"
        },
        "b3": {
          "s": 4,
          "r": "8",
          "rpe": "7-8",
          "l": "moderada",
          "rest": "2 min"
        },
        "dl": {
          "s": 2,
          "r": "10",
          "rpe": "5",
          "l": "carga B2",
          "rest": "2 min"
        }
      }, {
        "pt": "CUIDADO COSTAS: RPE máx. 8 mesmo no bloco pesado. Técnica primeiro.",
        "en": "BACK CAUTION: RPE 8 max even in the heavy block. Technique first."
      }),
    I("legcurl_seat", prog(4, "25 kg cal", "60–90 s", "iso")),
    I("legpress_h", prog(3, "60 kg cal", "2 min", "comp")),
    I("calf_seat", prog(4, "30 kg cal", "45–60 s", "iso")),
    I("pallof", {
        "b1": {
          "s": 3,
          "r": "10/lado",
          "rpe": "—",
          "l": "15 kg cal",
          "rest": "45 s"
        },
        "b2": {
          "s": 3,
          "r": "10/lado",
          "rpe": "—",
          "l": "base + carga",
          "rest": "45 s"
        },
        "b3": {
          "s": 3,
          "r": "12/lado",
          "rpe": "—",
          "l": "pesada",
          "rest": "45 s"
        },
        "dl": {
          "s": 2,
          "r": "8/lado",
          "rpe": "—",
          "l": "carga B2",
          "rest": "45 s"
        }
      }, {
        "pt": "Complementar de core (anti-rotação).",
        "en": "Core accessory (anti-rotation)."
      }),
    ],
  },
  {
    "id": 6,
    "wd": {
      "pt": "Sáb",
      "en": "Sat"
    },
    "ic": "",
    "theme": "cardio",
    "name": {
      "pt": "Cardio + Core",
      "en": "Cardio + Core"
    },
    "short": {
      "pt": "Cardio",
      "en": "Cardio"
    },
    "eyebrow": {
      "pt": "Dia 6 · Condicionamento",
      "en": "Day 6 · Conditioning"
    },
    "mus": {
      "pt": [
        "Sistema cardiovascular",
        "Abdómen",
        "Oblíquos"
      ],
      "en": [
        "Cardiovascular system",
        "Abs",
        "Obliques"
      ]
    },
    "type": "cardio",
    "warm": {
      "pt": "5 min de caminhada leve a subir o ritmo antes do cardio principal.",
      "en": "5 min easy walk, building pace before the main cardio."
    },
    "goal": {
      "pt": "Cardio de baixo impacto para acelerar a perda de gordura + trabalho de core. Complementar, sem prejudicar as pernas.",
      "en": "Low-impact cardio to speed up fat loss plus core work. Accessory only — it should not tax the legs."
    },
    "cardio": [
      "treadmill",
      "bike"
    ],
    "items": [
    I("plank", prog(3, "peso corporal", "45 s", "core")),
    I("legraise", prog(3, "peso corporal", "60 s", "acc")),
    I("cablecrunch", prog(3, "— preencher", "60 s", "acc")),
    I("pallof", {
        "b1": {
          "s": 3,
          "r": "10/lado",
          "rpe": "—",
          "l": "15 kg cal",
          "rest": "45 s"
        },
        "b2": {
          "s": 3,
          "r": "10/lado",
          "rpe": "—",
          "l": "base + carga",
          "rest": "45 s"
        },
        "b3": {
          "s": 3,
          "r": "12/lado",
          "rpe": "—",
          "l": "pesada",
          "rest": "45 s"
        },
        "dl": {
          "s": 2,
          "r": "8/lado",
          "rpe": "—",
          "l": "carga B2",
          "rest": "45 s"
        }
      }),
    ],
  },
  {
    "id": 7,
    "wd": {
      "pt": "Dom",
      "en": "Sun"
    },
    "ic": "",
    "theme": "rest",
    "name": {
      "pt": "Descanso / Recuperação",
      "en": "Rest / Recovery"
    },
    "short": {
      "pt": "Descanso",
      "en": "Rest"
    },
    "eyebrow": {
      "pt": "Dia 7 · Off",
      "en": "Day 7 · Off"
    },
    "mus": {
      "pt": [],
      "en": []
    },
    "type": "rest",
  }
];
