/**
 * A semana partilhada, autorada. NÃO é gerado — não corras `scripts/port-content.mjs`
 * por cima deste ficheiro.
 *
 * Este ficheiro dizia "GENERATED by scripts/port-content.mjs from old/js/data.js" e
 * isso deixou de ser verdade a 2026-09-21. A app é nova e `old/` não é fonte de nada:
 * a pasta fica no disco e não se lê. O que a app prescreve é autorado a partir do
 * protótipo aprovado em `proto/v2/`.
 *
 * A semana é a ordem dele de 2026-09-21, "para todas as contas":
 *
 *   Seg  Peito + Tríceps        Ter  Perna              Qua  Costas + Bíceps
 *   Qui  Descanso               Sex  Ombro + Bíceps + Perna
 *   Sáb  Full Body              Dom  Descanso
 *
 * O Dia 6 é a combinação de todos, em palavras dele: "peito + costa + bíceps +
 * shoulder + triceps + legs" e "full body é 3 exercícios por grupo". Seis grupos,
 * três exercícios cada — 18 exercícios, 60 séries, desenhados no frame 6 de
 * `proto/v2/03-treino.html` e aprovados no browser antes de chegarem aqui.
 *
 * As prescrições não foram reescritas. A semana nova MOVE exercícios entre dias; as
 * séries, reps, RPE, cargas, descansos e notas bilingues de cada um são as mesmas que
 * já estavam prescritas, byte a byte. Não se "melhoram" estes números: são o plano de
 * treino dele, não copy.
 */

import { prog } from './blocks';
import type { Day, DayItem, LocalizedText, SlotPrescriptions } from './schema';

const I = (ex: string, slots: SlotPrescriptions, note?: LocalizedText): DayItem => ({
  ex,
  ...slots,
  ...(note ? { note } : {}),
});

export const DAYS: readonly Day[] = [
  {
    "id": 1,
    "wd": {
      "pt": "Seg",
      "en": "Mon"
    },
    "ic": "",
    "theme": "push",
    "name": {
      "pt": "Peito + Tríceps",
      "en": "Chest + Triceps"
    },
    "short": {
      "pt": "Peito",
      "en": "Chest"
    },
    "eyebrow": {
      "pt": "Dia 1 · Push",
      "en": "Day 1 · Push"
    },
    "mus": {
      "pt": [
        "Peitoral",
        "Tríceps",
        "Deltoide anterior"
      ],
      "en": [
        "Chest",
        "Triceps",
        "Front delts"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min elíptica ou remo leve + rotações de ombro + 2 séries de aproximação no supino com halteres. Aquece bem os cotovelos antes das extensões.",
      "en": "6–8 min easy elliptical or rower + shoulder rotations + 2 ramp-up sets on the dumbbell bench. Warm the elbows well before the extensions."
    },
    "goal": {
      "pt": "Empurrar. O peito primeiro, com os compostos enquanto estás fresco; o tríceps a seguir, que já entra meio aquecido do supino. Os isolamentos ficam para o fim.",
      "en": "Pushing. Chest first, compounds while you are fresh; triceps next, already half-warm from the bench. Isolation work goes last."
    },
    "items": [
    I("dbbench", prog(4, "14 kg/mão cal", "2–3 min", "comp")),
    I("incldb", prog(3, "12 kg/mão cal", "2 min", "comp")),
    I("pecdeck", prog(3, "25 kg cal", "60–90 s", "iso")),
    I("cgbench", prog(4, "— preencher", "2–3 min", "comp")),
    I("ohext", prog(4, "— preencher", "90 s", "acc"), {
        "pt": "Prioridade do dia: acima da cabeça alonga a cabeça longa, e é aí que ela mais cresce.",
        "en": "Priority of the day: overhead lengthens the long head, and that is where it grows most."
      }),
    I("pushdown", prog(3, "20 kg cal", "60–90 s", "acc")),
    ],
  },
  {
    "id": 2,
    "wd": {
      "pt": "Ter",
      "en": "Tue"
    },
    "ic": "",
    "theme": "q",
    "name": {
      "pt": "Perna",
      "en": "Legs"
    },
    "short": {
      "pt": "Perna",
      "en": "Legs"
    },
    "eyebrow": {
      "pt": "Dia 2 · Inferior",
      "en": "Day 2 · Lower"
    },
    "mus": {
      "pt": [
        "Quadríceps",
        "Glúteo",
        "Isquiotibiais",
        "Panturrilha"
      ],
      "en": [
        "Quads",
        "Glutes",
        "Hamstrings",
        "Calves"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min bike + 1–2 séries de aproximação no Leg Press. Mobilidade de anca e joelho.",
      "en": "6–8 min bike + 1–2 ramp-up sets on the Leg Press. Hip and knee mobility."
    },
    "goal": {
      "pt": "A perna inteira num dia: quadríceps nos compostos, glúteo e posterior no fim. É o dia mais pesado da semana, e tem a quinta a seguir para recuperar.",
      "en": "The whole leg in one day: quads in the compounds, glutes and hamstrings at the end. It is the heaviest day of the week, and Thursday comes next to recover."
    },
    "items": [
    I("legpress", prog(4, "60 kg cal", "2–3 min", "comp")),
    I("hack", prog(3, "— preencher", "2 min", "comp"), {
        "pt": "Alternativa: Agachamento Goblet se não houver máquina Hack.",
        "en": "Alternative: Goblet Squat if there is no Hack machine."
      }),
    I("legext", prog(3, "25 kg cal", "60–90 s", "iso")),
    I("calf_s", prog(4, "40 kg cal", "45–60 s", "iso")),
    I("hipthrust", prog(4, "40 kg cal", "2–3 min", "comp")),
    I("legcurl_seat", prog(4, "25 kg cal", "60–90 s", "iso")),
    ],
  },
  {
    "id": 3,
    "wd": {
      "pt": "Qua",
      "en": "Wed"
    },
    "ic": "",
    "theme": "back",
    "name": {
      "pt": "Costas + Bíceps",
      "en": "Back + Biceps"
    },
    "short": {
      "pt": "Costas",
      "en": "Back"
    },
    "eyebrow": {
      "pt": "Dia 3 · Pull",
      "en": "Day 3 · Pull"
    },
    "mus": {
      "pt": [
        "Dorsal",
        "Trapézio",
        "Bíceps"
      ],
      "en": [
        "Lats",
        "Traps",
        "Biceps"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min remo leve + 2 séries de aproximação na puxada. Solta os ombros antes de puxar a sério.",
      "en": "6–8 min easy rowing + 2 ramp-up sets on the pulldown. Loosen the shoulders before pulling heavy."
    },
    "goal": {
      "pt": "Puxar. As costas nos compostos e o bíceps a seguir, que já trabalhou em todas as puxadas — é por isso que são dois exercícios de rosca e não quatro.",
      "en": "Pulling. Back in the compounds, then biceps, which already worked in every pull — which is why it is two curl exercises and not four."
    },
    "items": [
    I("pulldown", prog(4, "40 kg cal", "2–3 min", "comp")),
    I("csrow", prog(3, "30 kg cal", "2 min", "comp")),
    I("seatedrow", prog(3, "35 kg cal", "90 s", "comp")),
    I("strarm", prog(3, "— preencher", "60–90 s", "acc")),
    I("dbcurl", prog(3, "10 kg/mão cal", "60–90 s", "acc")),
    I("hammer", prog(3, "10 kg/mão cal", "60–90 s", "acc")),
    ],
  },
  {
    "id": 4,
    "wd": {
      "pt": "Qui",
      "en": "Thu"
    },
    "ic": "",
    "theme": "rest",
    "name": {
      "pt": "Descanso / Recuperação",
      "en": "Rest / Recovery"
    },
    "short": {
      "pt": "Descanso",
      "en": "Rest"
    },
    "eyebrow": {
      "pt": "Dia 4 · Off",
      "en": "Day 4 · Off"
    },
    "mus": {
      "pt": [],
      "en": []
    },
    "type": "rest",
  },
  {
    "id": 5,
    "wd": {
      "pt": "Sex",
      "en": "Fri"
    },
    "ic": "",
    "theme": "sh",
    "name": {
      "pt": "Ombro + Bíceps + Perna",
      "en": "Shoulders + Biceps + Legs"
    },
    "short": {
      "pt": "Ombro",
      "en": "Shoulders"
    },
    "eyebrow": {
      "pt": "Dia 5 · Push/Pull + Inferior",
      "en": "Day 5 · Push/Pull + Lower"
    },
    "mus": {
      "pt": [
        "Deltoides",
        "Bíceps",
        "Quadríceps",
        "Panturrilha"
      ],
      "en": [
        "Delts",
        "Biceps",
        "Quads",
        "Calves"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "6–8 min elíptica + rotações externas de ombro e 2 séries leves de elevação lateral. A perna entra no fim, já aquecida pelo resto.",
      "en": "6–8 min elliptical + external shoulder rotations and 2 light lateral raise sets. Legs come at the end, already warm from the rest."
    },
    "goal": {
      "pt": "Ombro à frente, bíceps no meio e um remate de perna. O volume de perna é curto de propósito: a terça já levou o dia pesado.",
      "en": "Shoulders first, biceps in the middle, and a leg finisher. Leg volume is deliberately short: Tuesday already took the heavy day."
    },
    "items": [
    I("dbohp", prog(4, "10 kg/mão cal", "2–3 min", "comp")),
    I("lateral", prog(4, "6 kg/mão cal", "45–60 s", "iso")),
    I("reardelt", prog(3, "— preencher", "60 s", "acc")),
    I("cablecurl", prog(2, "— preencher", "60 s", "acc"), {
        "pt": "Finalizador de bíceps com tensão constante.",
        "en": "Biceps finisher with constant tension."
      }),
    I("lunge", prog(3, "10 kg/mão cal", "90 s", "acc")),
    I("calf_seat", prog(4, "30 kg cal", "45–60 s", "iso")),
    ],
  },
  {
    "id": 6,
    "wd": {
      "pt": "Sáb",
      "en": "Sat"
    },
    "ic": "",
    "theme": "full",
    "name": {
      "pt": "Full Body",
      "en": "Full Body"
    },
    "short": {
      "pt": "Full Body",
      "en": "Full Body"
    },
    "eyebrow": {
      "pt": "Dia 6 · Corpo inteiro",
      "en": "Day 6 · Full body"
    },
    "mus": {
      "pt": [
        "Peitoral",
        "Dorsal",
        "Deltoides",
        "Quadríceps",
        "Bíceps",
        "Tríceps"
      ],
      "en": [
        "Chest",
        "Lats",
        "Delts",
        "Quads",
        "Biceps",
        "Triceps"
      ]
    },
    "type": "strength",
    "warm": {
      "pt": "10 min: bike ou remo + mobilidade de ombro, anca e joelho. É o dia mais longo da semana — aquece o corpo todo, não só o primeiro exercício.",
      "en": "10 min: bike or rower + shoulder, hip and knee mobility. It is the longest day of the week — warm the whole body, not just the first exercise."
    },
    "goal": {
      "pt": "Seis grupos, três exercícios cada: 18 exercícios e 60 séries. Dentro de cada grupo o composto vem primeiro e o isolamento no fim. Com os descansos prescritos, conta 2h30 a 3h.",
      "en": "Six groups, three exercises each: 18 exercises and 60 sets. Within each group the compound comes first and the isolation last. With the prescribed rest, budget 2h30 to 3h."
    },
    "items": [
    I("dbbench", prog(4, "14 kg/mão cal", "2–3 min", "comp")),
    I("incldb", prog(3, "12 kg/mão cal", "2 min", "comp")),
    I("pecdeck", prog(3, "25 kg cal", "60–90 s", "iso")),
    I("pulldown", prog(4, "40 kg cal", "2–3 min", "comp")),
    I("csrow", prog(3, "30 kg cal", "2 min", "comp")),
    I("seatedrow", prog(3, "35 kg cal", "90 s", "comp")),
    I("dbohp", prog(4, "10 kg/mão cal", "2–3 min", "comp")),
    I("lateral", prog(4, "6 kg/mão cal", "45–60 s", "iso")),
    I("reardelt", prog(3, "— preencher", "60 s", "acc")),
    I("legpress", prog(4, "60 kg cal", "2–3 min", "comp")),
    I("legext", prog(3, "25 kg cal", "60–90 s", "iso")),
    I("legcurl_seat", prog(4, "25 kg cal", "60–90 s", "iso")),
    I("dbcurl", prog(3, "10 kg/mão cal", "60–90 s", "acc")),
    I("hammer", prog(3, "10 kg/mão cal", "60–90 s", "acc")),
    I("cablecurl", prog(2, "— preencher", "60 s", "acc"), {
        "pt": "Finalizador de bíceps com tensão constante.",
        "en": "Biceps finisher with constant tension."
      }),
    I("cgbench", prog(4, "— preencher", "2–3 min", "comp")),
    I("pushdown", prog(3, "20 kg cal", "60–90 s", "acc")),
    I("skull", prog(3, "— preencher", "60–90 s", "acc")),
    ],
  },
  {
    "id": 7,
    "wd": {
      "pt": "Dom",
      "en": "Sun"
    },
    "ic": "",
    "theme": "rest",
    "name": {
      "pt": "Descanso / Recuperação",
      "en": "Rest / Recovery"
    },
    "short": {
      "pt": "Descanso",
      "en": "Rest"
    },
    "eyebrow": {
      "pt": "Dia 7 · Off",
      "en": "Day 7 · Off"
    },
    "mus": {
      "pt": [],
      "en": []
    },
    "type": "rest",
  }
];
