/**
 * GENERATED by scripts/port-content.mjs from old/js/data.js. Do not edit by hand.
 *
 * This is the authored training programme, ported verbatim. The source file's own
 * header says it plainly: do not "improve" these. Rep ranges, loads, RPE targets and
 * every line of bilingual technique text are the user's training plan, not copy.
 */

import type { Exercise } from './schema';

export const EXERCISES: Readonly<Record<string, Exercise>> = {
  "legpress": {
    "nPT": "Leg Press 45°",
    "nEN": "Leg Press",
    "eq": {
      "pt": "Leg Press 45°",
      "en": "45° Leg Press"
    },
    "anim": "legpress",
    "pri": [
      "quads",
      "glutes"
    ],
    "sec": [
      "hamstrings",
      "calves"
    ],
    "steps": {
      "pt": [
        "Senta com costas e bacia totalmente apoiadas no encosto.",
        "Pés à largura dos ombros, a meia altura da plataforma.",
        "Destrava as travas e controla a descida.",
        "Desce até ~90° de joelho, sem tirar a lombar do encosto.",
        "Empurra pela planta do pé até quase estender, sem travar os joelhos."
      ],
      "en": [
        "Sit with your back and hips fully against the pad.",
        "Feet shoulder-width, mid-height on the platform.",
        "Release the safety catches and control the descent.",
        "Lower to about 90° of knee bend without letting your lower back lift.",
        "Push through the whole foot to near lockout, without snapping the knees."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Lombar sai do encosto no fundo (coluna arredonda).",
          "c": "Reduz a amplitude: desce só até onde a bacia se mantém apoiada."
        },
        {
          "e": "Travar/estalar os joelhos no topo.",
          "c": "Pára a ~5° da extensão total, tensão contínua."
        },
        {
          "e": "Joelhos colapsam para dentro.",
          "c": "Empurra os joelhos para fora, alinhados com os pés."
        }
      ],
      "en": [
        {
          "e": "Lower back lifts off the pad at the bottom (spine rounds).",
          "c": "Cut the range: only go as deep as your hips stay supported."
        },
        {
          "e": "Locking/snapping the knees at the top.",
          "c": "Stop about 5° short of full extension, keep tension."
        },
        {
          "e": "Knees caving inward.",
          "c": "Push the knees out, in line with your feet."
        }
      ]
    },
    "safe": {
      "pt": [
        "Mantém a lombar colada ao encosto — chave para as tuas costas.",
        "Usa sempre as travas de segurança."
      ],
      "en": [
        "Keep the lower back glued to the pad — key for your back.",
        "Always use the safety catches."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao empurrar.",
      "en": "Breathe in as you lower, out as you press."
    }
  },
  "hack": {
    "nPT": "Agachamento Hack",
    "nEN": "Hack Squat",
    "eq": {
      "pt": "Máquina Hack",
      "en": "Hack machine"
    },
    "anim": "squat",
    "pri": [
      "quads"
    ],
    "sec": [
      "glutes"
    ],
    "steps": {
      "pt": [
        "Ombros sob as almofadas, costas apoiadas no encosto.",
        "Pés à largura dos ombros, a meio da plataforma.",
        "Destrava e desce controlando até ~90°.",
        "Mantém a coluna neutra colada ao encosto.",
        "Empurra pelos calcanhares até quase estender."
      ],
      "en": [
        "Shoulders under the pads, back flat against the backrest.",
        "Feet shoulder-width, mid-platform.",
        "Unrack and lower under control to about 90°.",
        "Keep a neutral spine pressed into the pad.",
        "Drive through the heels to near lockout."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Levantar os calcanhares na descida.",
          "c": "Distribui o peso no pé todo; ajusta os pés mais à frente."
        },
        {
          "e": "Descer rápido sem controlo.",
          "c": "2 segundos na descida, controla sempre."
        },
        {
          "e": "Descolar a lombar do encosto.",
          "c": "Não desças além do que mantém as costas apoiadas."
        }
      ],
      "en": [
        {
          "e": "Heels lifting on the way down.",
          "c": "Spread the weight over the whole foot; move your feet further forward."
        },
        {
          "e": "Dropping fast with no control.",
          "c": "Two seconds down, always controlled."
        },
        {
          "e": "Lower back peeling off the pad.",
          "c": "Do not go deeper than your back stays supported."
        }
      ]
    },
    "safe": {
      "pt": [
        "Encosto protege a coluna — mantém o contacto total.",
        "Começa leve para dominar a trajetória."
      ],
      "en": [
        "The backrest protects your spine — keep full contact.",
        "Start light until the groove feels natural."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao subir.",
      "en": "Breathe in on the way down, out on the way up."
    }
  },
  "legext": {
    "nPT": "Cadeira Extensora",
    "nEN": "Leg Extension",
    "eq": {
      "pt": "Máquina Extensora",
      "en": "Leg extension machine"
    },
    "anim": "legext",
    "pri": [
      "quads"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "Ajusta o encosto: joelho alinhado ao eixo da máquina.",
        "Almofada na parte baixa da canela, acima do pé.",
        "Segura os apoios laterais.",
        "Estende as pernas controlado até quase à extensão.",
        "Segura 1s no topo e desce devagar."
      ],
      "en": [
        "Set the backrest so your knee lines up with the machine pivot.",
        "Pad low on the shin, just above the foot.",
        "Hold the side handles.",
        "Extend the legs under control to near full extension.",
        "Hold for 1s at the top and lower slowly."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Balançar o corpo para gerar impulso.",
          "c": "Fixa a bacia no banco; só o joelho se move."
        },
        {
          "e": "Descer a carga em queda livre.",
          "c": "Controla a fase negativa (2s)."
        }
      ],
      "en": [
        {
          "e": "Swinging the body to create momentum.",
          "c": "Pin your hips to the seat; only the knee moves."
        },
        {
          "e": "Letting the weight drop freely.",
          "c": "Control the negative (2s)."
        }
      ]
    },
    "safe": {
      "pt": [
        "Negativa lenta protege o joelho.",
        "Sem impulso — isola o quadríceps."
      ],
      "en": [
        "A slow negative protects the knee.",
        "No momentum — isolate the quads."
      ]
    },
    "breath": {
      "pt": "Expira ao estender, inspira ao descer.",
      "en": "Breathe out as you extend, in as you lower."
    }
  },
  "lunge": {
    "nPT": "Afundo com Halteres",
    "nEN": "Dumbbell Lunge",
    "eq": {
      "pt": "Halteres",
      "en": "Dumbbells"
    },
    "anim": "squat",
    "pri": [
      "quads",
      "glutes"
    ],
    "sec": [
      "hamstrings"
    ],
    "steps": {
      "pt": [
        "Em pé, um haltere em cada mão ao lado do corpo.",
        "Dá um passo à frente e desce a bacia na vertical.",
        "Joelho de trás quase a tocar o chão, tronco erguido.",
        "O joelho da frente alinha com o pé, sem passar muito.",
        "Empurra pelo calcanhar da frente para voltar."
      ],
      "en": [
        "Stand with a dumbbell in each hand at your sides.",
        "Step forward and drop your hips straight down.",
        "Back knee almost touching the floor, chest tall.",
        "Front knee tracks over the foot, without drifting far past it.",
        "Push through the front heel to come back."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Tronco inclinado à frente.",
          "c": "Peito erguido, olhar em frente, core firme."
        },
        {
          "e": "Passada curta (joelho passa o pé).",
          "c": "Passo mais longo; desce na vertical."
        }
      ],
      "en": [
        {
          "e": "Torso leaning forward.",
          "c": "Chest up, eyes ahead, core braced."
        },
        {
          "e": "Step too short (knee shoots past the foot).",
          "c": "Take a longer step; drop straight down."
        }
      ]
    },
    "safe": {
      "pt": [
        "Core firme protege a lombar.",
        "Se o equilíbrio falhar, apoia-te ligeiramente."
      ],
      "en": [
        "A braced core protects your lower back.",
        "If balance fails, hold on lightly for support."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao subir.",
      "en": "Breathe in on the way down, out on the way up."
    }
  },
  "calf_s": {
    "nPT": "Elevação de Panturrilha em Pé",
    "nEN": "Standing Calf Raise",
    "eq": {
      "pt": "Máquina de Panturrilha",
      "en": "Calf raise machine"
    },
    "anim": "calf",
    "pri": [
      "calves"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "Ombros sob as almofadas, ponta dos pés na plataforma.",
        "Deixa os calcanhares descerem abaixo da linha (alongar).",
        "Sobe na ponta dos pés o mais alto possível.",
        "Segura 1s no topo.",
        "Desce devagar controlando."
      ],
      "en": [
        "Shoulders under the pads, balls of the feet on the platform.",
        "Let the heels drop below the platform line (stretch).",
        "Rise onto the toes as high as you can.",
        "Hold for 1s at the top.",
        "Lower slowly under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Amplitude curta.",
          "c": "Alonga em baixo e contrai no topo, amplitude total."
        },
        {
          "e": "Saltar em vez de controlar.",
          "c": "Movimento lento e deliberado."
        }
      ],
      "en": [
        {
          "e": "Short range of motion.",
          "c": "Stretch at the bottom, squeeze at the top — full range."
        },
        {
          "e": "Bouncing instead of controlling.",
          "c": "Slow, deliberate movement."
        }
      ]
    },
    "safe": {
      "pt": [
        "Movimento controlado, sem ressaltos."
      ],
      "en": [
        "Controlled movement, no bouncing."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you rise, in as you lower."
    }
  },
  "plank": {
    "nPT": "Prancha",
    "nEN": "Plank",
    "eq": {
      "pt": "Peso corporal",
      "en": "Bodyweight"
    },
    "anim": "plank",
    "pri": [
      "abs"
    ],
    "sec": [
      "obliques",
      "lowerBack"
    ],
    "steps": {
      "pt": [
        "Antebraços no chão, cotovelos sob os ombros.",
        "Pés à largura da bacia, corpo em linha reta.",
        "Contrai abdómen e glúteos.",
        "Bacia levemente enrolada, costelas para baixo.",
        "Mantém o tempo alvo respirando normalmente."
      ],
      "en": [
        "Forearms on the floor, elbows under the shoulders.",
        "Feet hip-width, body in a straight line.",
        "Squeeze abs and glutes.",
        "Tuck the pelvis slightly, ribs down.",
        "Hold for the target time, breathing normally."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Bacia muito alta ou muito baixa.",
          "c": "Linha reta ombro-bacia-tornozelo."
        },
        {
          "e": "Prender a respiração.",
          "c": "Respira de forma contínua e lenta."
        }
      ],
      "en": [
        {
          "e": "Hips too high or sagging too low.",
          "c": "Straight line from shoulder to hip to ankle."
        },
        {
          "e": "Holding your breath.",
          "c": "Breathe continuously and slowly."
        }
      ]
    },
    "safe": {
      "pt": [
        "Linha reta protege a lombar; pára se ceder."
      ],
      "en": [
        "A straight line protects your lower back; stop when it sags."
      ]
    },
    "breath": {
      "pt": "Respira continuamente — nunca prendas o ar.",
      "en": "Keep breathing — never hold your breath."
    }
  },
  "dbbench": {
    "nPT": "Supino com Halteres",
    "nEN": "Dumbbell Bench Press",
    "eq": {
      "pt": "Halteres + Banco",
      "en": "Dumbbells + Bench"
    },
    "anim": "benchpress",
    "pri": [
      "chest"
    ],
    "sec": [
      "frontDelt",
      "triceps"
    ],
    "steps": {
      "pt": [
        "Deita no banco, halteres à altura do peito.",
        "Escápulas retraídas, pés firmes no chão.",
        "Cotovelos a ~45° do tronco.",
        "Empurra até quase estender, sem bater os halteres.",
        "Desce controlando até alongar o peito."
      ],
      "en": [
        "Lie on the bench with the dumbbells at chest level.",
        "Shoulder blades retracted, feet planted.",
        "Elbows at about 45° to the torso.",
        "Press to near lockout without clashing the dumbbells.",
        "Lower under control until the chest stretches."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Cotovelos abertos a 90° (stress no ombro).",
          "c": "Mantém ~45° entre braço e tronco."
        },
        {
          "e": "Arquear muito a lombar.",
          "c": "Costelas para baixo, ligeiro arco natural apenas."
        }
      ],
      "en": [
        {
          "e": "Elbows flared to 90° (shoulder stress).",
          "c": "Keep about 45° between arm and torso."
        },
        {
          "e": "Over-arching the lower back.",
          "c": "Ribs down, only a slight natural arch."
        }
      ]
    },
    "safe": {
      "pt": [
        "Desce só até a amplitude confortável do ombro."
      ],
      "en": [
        "Only lower as far as your shoulder is comfortable."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao empurrar.",
      "en": "Breathe in as you lower, out as you press."
    }
  },
  "incldb": {
    "nPT": "Supino Inclinado com Halteres",
    "nEN": "Incline DB Press",
    "eq": {
      "pt": "Halteres + Banco inclinado 30°",
      "en": "Dumbbells + 30° incline bench"
    },
    "anim": "incline",
    "pri": [
      "chest"
    ],
    "sec": [
      "frontDelt",
      "triceps"
    ],
    "steps": {
      "pt": [
        "Banco inclinado a ~30°.",
        "Halteres à altura do peito superior.",
        "Escápulas retraídas, pés firmes.",
        "Empurra para cima e ligeiramente para dentro.",
        "Desce controlando ao peito superior."
      ],
      "en": [
        "Set the bench to about 30°.",
        "Dumbbells at upper-chest level.",
        "Shoulder blades retracted, feet planted.",
        "Press up and slightly inward.",
        "Lower under control to the upper chest."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Inclinação demasiado alta (>45°).",
          "c": "Fica em ~30° para focar o peito, não o ombro."
        },
        {
          "e": "Descer pouco.",
          "c": "Amplitude completa até alongar."
        }
      ],
      "en": [
        {
          "e": "Bench angle too steep (>45°).",
          "c": "Stay near 30° to hit chest, not shoulders."
        },
        {
          "e": "Not lowering far enough.",
          "c": "Full range, down to a stretch."
        }
      ]
    },
    "safe": {
      "pt": [
        "Inclinação moderada poupa o ombro."
      ],
      "en": [
        "A moderate incline spares the shoulder."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao empurrar.",
      "en": "Breathe in as you lower, out as you press."
    }
  },
  "pecdeck": {
    "nPT": "Peck Deck",
    "nEN": "Pec Deck / Machine Fly",
    "eq": {
      "pt": "Máquina Peck Deck",
      "en": "Pec deck machine"
    },
    "anim": "benchpress",
    "pri": [
      "chest"
    ],
    "sec": [
      "frontDelt"
    ],
    "steps": {
      "pt": [
        "Ajusta o assento: pegas à altura do meio do peito.",
        "Costas apoiadas, antebraços nas almofadas.",
        "Junta os braços à frente contraindo o peito.",
        "Segura 1s na contração.",
        "Volta controlando sem bater os pesos."
      ],
      "en": [
        "Set the seat so the handles sit at mid-chest height.",
        "Back against the pad, forearms on the pads.",
        "Bring the arms together in front, squeezing the chest.",
        "Hold the squeeze for 1s.",
        "Return under control without clanging the stack."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Assento mal ajustado (pegas altas).",
          "c": "Pegas ao nível do meio do peito."
        },
        {
          "e": "Usar impulso.",
          "c": "Movimento controlado, foco no peito."
        }
      ],
      "en": [
        {
          "e": "Seat set wrong (handles too high).",
          "c": "Handles at mid-chest level."
        },
        {
          "e": "Using momentum.",
          "c": "Controlled movement, focus on the chest."
        }
      ]
    },
    "safe": {
      "pt": [
        "Não forces a abertura para trás do plano do corpo."
      ],
      "en": [
        "Do not force the stretch behind the plane of your body."
      ]
    },
    "breath": {
      "pt": "Expira ao juntar, inspira ao abrir.",
      "en": "Breathe out as you close, in as you open."
    }
  },
  "pushdown": {
    "nPT": "Tríceps na Polia",
    "nEN": "Triceps Pushdown",
    "eq": {
      "pt": "Polia alta + barra/corda",
      "en": "High pulley + bar/rope"
    },
    "anim": "pushdown",
    "pri": [
      "triceps"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "Polia no alto, pega pronada.",
        "Cotovelos junto ao tronco, fixos.",
        "Estende os cotovelos empurrando para baixo.",
        "Segura 1s em baixo.",
        "Sobe controlando."
      ],
      "en": [
        "Pulley set high, overhand grip.",
        "Elbows pinned to your sides.",
        "Extend the elbows, pushing down.",
        "Hold for 1s at the bottom.",
        "Return under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Afastar os cotovelos do corpo.",
          "c": "Cotovelos colados ao tronco, fixos."
        },
        {
          "e": "Inclinar o tronco para empurrar.",
          "c": "Tronco direito; só o antebraço se move."
        }
      ],
      "en": [
        {
          "e": "Elbows drifting away from the body.",
          "c": "Elbows glued to the torso, fixed."
        },
        {
          "e": "Leaning over to push the weight.",
          "c": "Stay upright; only the forearm moves."
        }
      ]
    },
    "safe": {
      "pt": [
        "Cotovelos fixos isolam o tríceps e poupam o ombro."
      ],
      "en": [
        "Fixed elbows isolate the triceps and spare the shoulder."
      ]
    },
    "breath": {
      "pt": "Expira ao estender, inspira ao subir.",
      "en": "Breathe out as you extend, in as you return."
    }
  },
  "ohext": {
    "nPT": "Extensão de Tríceps acima da cabeça",
    "nEN": "Overhead Cable Extension",
    "eq": {
      "pt": "Polia + corda",
      "en": "Cable + rope"
    },
    "anim": "ohext",
    "pri": [
      "triceps"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "De costas para a polia (na posição baixa/alta com corda).",
        "Corda atrás da cabeça, cotovelos apontados à frente e para cima.",
        "Estende os cotovelos à frente até quase esticar.",
        "Contrai o tríceps no fim.",
        "Volta controlando alongando o tríceps."
      ],
      "en": [
        "Face away from the pulley (rope attached low or high).",
        "Rope behind your head, elbows pointing forward and up.",
        "Extend the elbows forward to near lockout.",
        "Squeeze the triceps at the end.",
        "Return under control, stretching the triceps."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Cotovelos abrem para os lados.",
          "c": "Mantém os cotovelos apontados à frente e juntos."
        },
        {
          "e": "Arquear a lombar ao estender.",
          "c": "Core firme, um pé à frente para estabilizar."
        }
      ],
      "en": [
        {
          "e": "Elbows flaring out to the sides.",
          "c": "Keep the elbows pointing forward and close together."
        },
        {
          "e": "Arching the lower back as you extend.",
          "c": "Brace the core, stagger one foot forward for stability."
        }
      ]
    },
    "safe": {
      "pt": [
        "Alonga o tríceps na posição de cima — bom estímulo, controla a carga."
      ],
      "en": [
        "This stretches the triceps overhead — great stimulus, keep the load controlled."
      ]
    },
    "breath": {
      "pt": "Expira ao estender, inspira ao voltar.",
      "en": "Breathe out as you extend, in as you return."
    }
  },
  "skull": {
    "nPT": "Tríceps Testa",
    "nEN": "Lying Triceps Extension / Skullcrusher",
    "eq": {
      "pt": "Barra EZ ou Halteres + Banco",
      "en": "EZ bar or dumbbells + bench"
    },
    "anim": "ohext",
    "pri": [
      "triceps"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "Deitado no banco, barra EZ (ou halteres) acima do peito, braços esticados.",
        "Cotovelos apontados para cima e fixos.",
        "Desce a barra em direção à testa flexionando só os cotovelos.",
        "Pára junto à testa/atrás da cabeça, sem abrir os cotovelos.",
        "Estende de volta ao topo contraindo o tríceps."
      ],
      "en": [
        "Lie on the bench, EZ bar (or dumbbells) over the chest, arms straight.",
        "Elbows pointing up and fixed.",
        "Lower the bar toward your forehead, bending only at the elbows.",
        "Stop near the forehead/behind the head without flaring the elbows.",
        "Extend back to the top, squeezing the triceps."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Abrir os cotovelos para os lados.",
          "c": "Cotovelos apontados ao teto e fixos durante todo o movimento."
        },
        {
          "e": "Mexer os ombros/braços (vira supino).",
          "c": "Só o antebraço se move; o braço fica imóvel."
        }
      ],
      "en": [
        {
          "e": "Flaring the elbows out to the sides.",
          "c": "Elbows pointed at the ceiling and fixed throughout."
        },
        {
          "e": "Moving the shoulders/upper arms (it turns into a press).",
          "c": "Only the forearm moves; the upper arm stays still."
        }
      ]
    },
    "safe": {
      "pt": [
        "Controla a descida junto à testa; carga moderada para proteger o cotovelo."
      ],
      "en": [
        "Control the descent near your forehead; moderate load to protect the elbow."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao estender.",
      "en": "Breathe in as you lower, out as you extend."
    }
  },
  "cgbench": {
    "nPT": "Supino Fechado",
    "nEN": "Close-Grip Bench Press",
    "eq": {
      "pt": "Barra + Banco",
      "en": "Barbell + bench"
    },
    "anim": "benchpress",
    "pri": [
      "triceps"
    ],
    "sec": [
      "chest",
      "frontDelt"
    ],
    "steps": {
      "pt": [
        "Deitado no banco, pega à largura dos ombros — não mais estreita.",
        "Punhos direitos por cima dos cotovelos.",
        "Cotovelos a ~45° do tronco, não abertos.",
        "Desce a barra à parte baixa do peito, a roçar.",
        "Empurra até quase estender, a pensar em estender o cotovelo."
      ],
      "en": [
        "Lie on the bench, grip at shoulder width — no narrower.",
        "Wrists stacked straight over the elbows.",
        "Elbows about 45° from the torso, not flared.",
        "Lower the bar to the lower chest, just touching.",
        "Press to near lockout, thinking about extending the elbow."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Pega demasiado estreita (mãos a tocar-se).",
          "c": "Largura dos ombros — mais estreito só castiga o punho, não recruta mais tríceps."
        },
        {
          "e": "Abrir os cotovelos como no supino normal.",
          "c": "Cotovelos junto ao tronco; é isso que transfere o trabalho para o tríceps."
        }
      ],
      "en": [
        {
          "e": "Gripping far too narrow (hands touching).",
          "c": "Shoulder width — narrower only punishes the wrist, it does not recruit more triceps."
        },
        {
          "e": "Flaring the elbows as in a regular bench press.",
          "c": "Elbows tucked; that is what shifts the work onto the triceps."
        }
      ]
    },
    "safe": {
      "pt": [
        "O composto mais pesado do dia — usa suportes de segurança ou um observador.",
        "Punho a doer é sinal de pega estreita demais."
      ],
      "en": [
        "The heaviest compound of the day — use safety pins or a spotter.",
        "Wrist pain means the grip is too narrow."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao empurrar.",
      "en": "Breathe in as you lower, out as you press."
    }
  },
  "dip": {
    "nPT": "Paralelas para Tríceps",
    "nEN": "Parallel Bar Dip",
    "eq": {
      "pt": "Paralelas (ou máquina assistida)",
      "en": "Parallel bars (or assisted machine)"
    },
    "anim": "pushdown",
    "pri": [
      "triceps"
    ],
    "sec": [
      "chest",
      "frontDelt"
    ],
    "steps": {
      "pt": [
        "Apoia-te nas barras, braços esticados, ombros para baixo.",
        "Tronco o mais vertical possível — inclinar à frente passa o trabalho para o peito.",
        "Cotovelos apontados atrás, junto ao corpo.",
        "Desce até ~90° de cotovelo.",
        "Empurra até estender sem travar."
      ],
      "en": [
        "Support yourself on the bars, arms straight, shoulders pulled down.",
        "Torso as upright as possible — leaning forward shifts the work to the chest.",
        "Elbows pointing back, close to the body.",
        "Lower to about 90° at the elbow.",
        "Press up to extension without snapping the elbows."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Descer demasiado, ombro à frente da linha do cotovelo.",
          "c": "Pára aos ~90° — mais fundo é onde o ombro se magoa."
        },
        {
          "e": "Ombros a subir até às orelhas.",
          "c": "Ombros para baixo e atrás antes de começar."
        }
      ],
      "en": [
        {
          "e": "Dropping too deep, shoulder passing below the elbow line.",
          "c": "Stop around 90° — deeper is where the shoulder gets hurt."
        },
        {
          "e": "Shoulders shrugging up to the ears.",
          "c": "Set the shoulders down and back before you start."
        }
      ]
    },
    "safe": {
      "pt": [
        "Se ainda não fazes com o peso do corpo, usa a máquina assistida — não vale a pena forçar.",
        "Qualquer dor à frente do ombro: pára e reduz a amplitude."
      ],
      "en": [
        "If bodyweight is not there yet, use the assisted machine — forcing it is not worth it.",
        "Any pain at the front of the shoulder: stop and shorten the range."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao subir.",
      "en": "Breathe in as you lower, out as you press up."
    }
  },
  "kickback": {
    "nPT": "Coice de Tríceps no Cabo",
    "nEN": "Cable Triceps Kickback",
    "eq": {
      "pt": "Polia baixa + pega",
      "en": "Low pulley + handle"
    },
    "anim": "pushdown",
    "pri": [
      "triceps"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "Polia em baixo, tronco inclinado à frente ~45°.",
        "Braço colado ao tronco, cotovelo a 90°.",
        "Estende só o cotovelo até o braço ficar a direito atrás.",
        "Segura 1s na contração máxima.",
        "Volta controlando até aos 90°."
      ],
      "en": [
        "Pulley set low, torso bent forward about 45°.",
        "Upper arm pinned to the torso, elbow at 90°.",
        "Extend only the elbow until the arm is straight behind you.",
        "Hold the peak contraction for 1s.",
        "Return under control to 90°."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "O braço todo balança em vez de só o antebraço.",
          "c": "Cotovelo fixo — se abana, a carga está alta demais."
        },
        {
          "e": "Usar carga pesada e perder a contração no fim.",
          "c": "É um finalizador: carga leve, aperta no fim."
        }
      ],
      "en": [
        {
          "e": "Swinging the whole arm instead of just the forearm.",
          "c": "Fix the elbow — if it swings, the load is too heavy."
        },
        {
          "e": "Going heavy and losing the squeeze at the end.",
          "c": "This is a finisher: light load, squeeze at the top."
        }
      ]
    },
    "safe": {
      "pt": [
        "Trabalho leve de fim de sessão; não há razão para forçar aqui."
      ],
      "en": [
        "Light end-of-session work; no reason to push hard here."
      ]
    },
    "breath": {
      "pt": "Expira ao estender, inspira ao voltar.",
      "en": "Breathe out as you extend, in as you return."
    }
  },
  "dbohp": {
    "nPT": "Desenvolvimento com Halteres",
    "nEN": "Dumbbell Shoulder Press",
    "eq": {
      "pt": "Halteres + Banco vertical",
      "en": "Dumbbells + upright bench"
    },
    "anim": "ohp",
    "pri": [
      "frontDelt"
    ],
    "sec": [
      "sideDelt",
      "triceps"
    ],
    "steps": {
      "pt": [
        "Sentado, encosto vertical, halteres à altura dos ombros.",
        "Punhos neutros, cotovelos ligeiramente à frente.",
        "Lombar apoiada no encosto.",
        "Empurra até quase estender, sem travar.",
        "Desce até os cotovelos ao nível dos ombros."
      ],
      "en": [
        "Seated, backrest upright, dumbbells at shoulder height.",
        "Neutral wrists, elbows slightly forward.",
        "Lower back supported by the pad.",
        "Press to near lockout, without snapping the elbows.",
        "Lower until the elbows reach shoulder level."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Arquear a lombar para empurrar mais peso.",
          "c": "Lombar apoiada; baixa a carga se compensas."
        },
        {
          "e": "Meia amplitude.",
          "c": "Desce até os ombros, sobe até quase esticar."
        }
      ],
      "en": [
        {
          "e": "Arching the lower back to press more weight.",
          "c": "Keep the back supported; drop the load if you compensate."
        },
        {
          "e": "Half range of motion.",
          "c": "Lower to the shoulders, press to near lockout."
        }
      ]
    },
    "safe": {
      "pt": [
        "Encosto apoiado protege a lombar.",
        "Sem dor no ombro — reduz amplitude se preciso."
      ],
      "en": [
        "A supported back protects your lumbar spine.",
        "No shoulder pain — shorten the range if needed."
      ]
    },
    "breath": {
      "pt": "Inspira em baixo, expira ao empurrar.",
      "en": "Breathe in at the bottom, out as you press."
    }
  },
  "lateral": {
    "nPT": "Elevação Lateral",
    "nEN": "Lateral Raise",
    "eq": {
      "pt": "Halteres",
      "en": "Dumbbells"
    },
    "anim": "lateral",
    "pri": [
      "sideDelt"
    ],
    "sec": [
      "traps"
    ],
    "steps": {
      "pt": [
        "Em pé, halteres ao lado do corpo.",
        "Cotovelos ligeiramente flexionados.",
        "Eleva para os lados até à altura dos ombros.",
        "Lidera com os cotovelos, não com as mãos.",
        "Desce devagar controlando."
      ],
      "en": [
        "Stand with the dumbbells at your sides.",
        "Elbows slightly bent.",
        "Raise out to the sides up to shoulder height.",
        "Lead with the elbows, not the hands.",
        "Lower slowly under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Peso a mais e balanço do corpo.",
          "c": "Carga leve; corpo imóvel, só os braços sobem."
        },
        {
          "e": "Subir acima dos ombros / encolher o trapézio.",
          "c": "Pára à altura dos ombros, ombros para baixo."
        }
      ],
      "en": [
        {
          "e": "Too much weight and body swing.",
          "c": "Go light; body still, only the arms rise."
        },
        {
          "e": "Going above shoulder height / shrugging the traps.",
          "c": "Stop at shoulder height, shoulders down."
        }
      ]
    },
    "safe": {
      "pt": [
        "Sem impulso; se balanças, baixa o peso."
      ],
      "en": [
        "No momentum; if you swing, drop the weight."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you raise, in as you lower."
    }
  },
  "reardelt": {
    "nPT": "Elevação Posterior",
    "nEN": "Reverse Fly",
    "eq": {
      "pt": "Halteres ou Máquina",
      "en": "Dumbbells or machine"
    },
    "anim": "reardelt",
    "pri": [
      "rearDelt"
    ],
    "sec": [
      "upperBack",
      "traps"
    ],
    "steps": {
      "pt": [
        "Tronco inclinado à frente (ou peito na almofada da máquina).",
        "Halteres pendentes, cotovelos levemente fletidos.",
        "Abre os braços para os lados e atrás.",
        "Aperta as omoplatas no fim.",
        "Volta controlando."
      ],
      "en": [
        "Hinge the torso forward (or chest on the machine pad).",
        "Dumbbells hanging, elbows slightly bent.",
        "Open the arms out to the sides and back.",
        "Squeeze the shoulder blades at the end.",
        "Return under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Usar os trapézios/encolher os ombros.",
          "c": "Ombros para baixo; foco na parte de trás do ombro."
        },
        {
          "e": "Peso excessivo com impulso.",
          "c": "Carga leve, movimento limpo."
        }
      ],
      "en": [
        {
          "e": "Using the traps/shrugging the shoulders.",
          "c": "Shoulders down; focus on the rear delt."
        },
        {
          "e": "Too heavy, using momentum.",
          "c": "Light load, clean movement."
        }
      ]
    },
    "safe": {
      "pt": [
        "Ótimo para postura — importante para quem passa 8h sentado."
      ],
      "en": [
        "Great for posture — important if you sit 8 hours a day."
      ]
    },
    "breath": {
      "pt": "Expira ao abrir, inspira ao voltar.",
      "en": "Breathe out as you open, in as you return."
    }
  },
  "dbcurl": {
    "nPT": "Rosca com Halteres",
    "nEN": "Dumbbell Curl",
    "eq": {
      "pt": "Halteres",
      "en": "Dumbbells"
    },
    "anim": "curl",
    "pri": [
      "biceps"
    ],
    "sec": [
      "forearm"
    ],
    "steps": {
      "pt": [
        "Em pé, halteres ao lado, palmas à frente.",
        "Cotovelos fixos junto ao tronco.",
        "Flexiona subindo até aos ombros.",
        "Segura 1s na contração.",
        "Desce controlando totalmente."
      ],
      "en": [
        "Stand with the dumbbells at your sides, palms forward.",
        "Elbows fixed against the torso.",
        "Curl up toward the shoulders.",
        "Hold the squeeze for 1s.",
        "Lower under full control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Balançar o corpo/lombar para subir.",
          "c": "Cotovelos fixos; se balanças, baixa o peso."
        },
        {
          "e": "Mover os cotovelos à frente.",
          "c": "Cotovelos imóveis ao lado do tronco."
        }
      ],
      "en": [
        {
          "e": "Swinging the body/lower back to lift.",
          "c": "Elbows fixed; if you swing, drop the weight."
        },
        {
          "e": "Letting the elbows drift forward.",
          "c": "Elbows stay still at your sides."
        }
      ]
    },
    "safe": {
      "pt": [
        "Sem balanço da lombar."
      ],
      "en": [
        "No swinging from the lower back."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you curl, in as you lower."
    }
  },
  "hammer": {
    "nPT": "Rosca Martelo",
    "nEN": "Hammer Curl",
    "eq": {
      "pt": "Halteres",
      "en": "Dumbbells"
    },
    "anim": "curl",
    "pri": [
      "biceps",
      "forearm"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "Em pé, pega neutra (palmas viradas uma para a outra).",
        "Cotovelos fixos ao lado do corpo.",
        "Flexiona mantendo a pega neutra até aos ombros.",
        "Segura 1s.",
        "Desce controlando."
      ],
      "en": [
        "Stand with a neutral grip (palms facing each other).",
        "Elbows fixed at your sides.",
        "Curl to the shoulders keeping the grip neutral.",
        "Hold for 1s.",
        "Lower under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Rodar o punho durante o movimento.",
          "c": "Mantém a pega neutra do início ao fim."
        },
        {
          "e": "Impulso da lombar.",
          "c": "Corpo imóvel, só o antebraço."
        }
      ],
      "en": [
        {
          "e": "Rotating the wrist during the rep.",
          "c": "Keep the grip neutral start to finish."
        },
        {
          "e": "Momentum from the lower back.",
          "c": "Body still, only the forearm moves."
        }
      ]
    },
    "safe": {
      "pt": [
        "Punho neutro alivia o cotovelo."
      ],
      "en": [
        "A neutral wrist is easier on the elbow."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you curl, in as you lower."
    }
  },
  "cablecurl": {
    "nPT": "Rosca no Cabo",
    "nEN": "Cable Curl",
    "eq": {
      "pt": "Polia baixa + barra",
      "en": "Low pulley + bar"
    },
    "anim": "curl",
    "pri": [
      "biceps"
    ],
    "sec": [
      "forearm"
    ],
    "steps": {
      "pt": [
        "Polia na posição baixa, pega a barra.",
        "Cotovelos fixos ao lado do tronco.",
        "Flexiona até aos ombros com tensão constante.",
        "Contrai no topo.",
        "Desce controlando."
      ],
      "en": [
        "Pulley set low, grip the bar.",
        "Elbows fixed at your sides.",
        "Curl to the shoulders with constant tension.",
        "Squeeze at the top.",
        "Lower under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Recuar o corpo para ajudar.",
          "c": "Pés firmes, tronco imóvel."
        },
        {
          "e": "Amplitude curta no topo.",
          "c": "Sobe até à contração completa."
        }
      ],
      "en": [
        {
          "e": "Leaning back to help the lift.",
          "c": "Feet planted, torso still."
        },
        {
          "e": "Cutting the range short at the top.",
          "c": "Curl all the way to full contraction."
        }
      ]
    },
    "safe": {
      "pt": [
        "O cabo mantém tensão constante — ótimo pico de contração."
      ],
      "en": [
        "The cable keeps constant tension — great peak contraction."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you curl, in as you lower."
    }
  },
  "pulldown": {
    "nPT": "Puxada na Polia Alta",
    "nEN": "Lat Pulldown",
    "eq": {
      "pt": "Polia alta + barra",
      "en": "High pulley + bar"
    },
    "anim": "pulldown",
    "pri": [
      "lats"
    ],
    "sec": [
      "biceps",
      "rearDelt"
    ],
    "steps": {
      "pt": [
        "Almofada das coxas firme para fixar o corpo.",
        "Pega um pouco mais larga que os ombros.",
        "Peito erguido, ligeira inclinação atrás.",
        "Puxa a barra ao peito, cotovelos para baixo e atrás.",
        "Sobe controlando até quase estender os braços."
      ],
      "en": [
        "Thigh pad snug to anchor your body.",
        "Grip slightly wider than shoulder-width.",
        "Chest up, a slight lean back.",
        "Pull the bar to your chest, elbows down and back.",
        "Let it rise under control to near full arm extension."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Puxar atrás da nuca.",
          "c": "Puxa sempre à frente, ao peito."
        },
        {
          "e": "Balançar o tronco para gerar impulso.",
          "c": "Tronco estável; puxa com as costas, não com o balanço."
        }
      ],
      "en": [
        {
          "e": "Pulling behind the neck.",
          "c": "Always pull in front, to the chest."
        },
        {
          "e": "Rocking the torso for momentum.",
          "c": "Torso steady; pull with your back, not with the swing."
        }
      ]
    },
    "safe": {
      "pt": [
        "Nunca atrás da nuca — protege ombros e pescoço."
      ],
      "en": [
        "Never behind the neck — protect your shoulders and neck."
      ]
    },
    "breath": {
      "pt": "Expira ao puxar, inspira ao subir.",
      "en": "Breathe out as you pull, in as it rises."
    }
  },
  "csrow": {
    "nPT": "Remada com Apoio de Peito",
    "nEN": "Chest-Supported Row",
    "eq": {
      "pt": "Máquina / Banco inclinado",
      "en": "Machine / incline bench"
    },
    "anim": "row",
    "pri": [
      "upperBack",
      "lats"
    ],
    "sec": [
      "biceps",
      "rearDelt"
    ],
    "steps": {
      "pt": [
        "Peito apoiado na almofada, pés firmes.",
        "Braços estendidos a segurar as alças.",
        "Puxa os cotovelos atrás, aperta as omoplatas.",
        "Segura 1s na contração.",
        "Volta controlando."
      ],
      "en": [
        "Chest against the pad, feet planted.",
        "Arms extended, holding the handles.",
        "Drive the elbows back, squeezing the shoulder blades.",
        "Hold the squeeze for 1s.",
        "Return under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Descolar o peito da almofada (usa a lombar).",
          "c": "Peito sempre apoiado — protege a coluna."
        },
        {
          "e": "Encolher os ombros.",
          "c": "Ombros para baixo, puxa com as costas."
        }
      ],
      "en": [
        {
          "e": "Lifting the chest off the pad (loading the lower back).",
          "c": "Chest stays on the pad — that is what protects your spine."
        },
        {
          "e": "Shrugging the shoulders.",
          "c": "Shoulders down, pull with the back."
        }
      ]
    },
    "safe": {
      "pt": [
        "Apoio de peito tira a carga da lombar — ideal para ti."
      ],
      "en": [
        "Chest support takes the load off your lower back — ideal for you."
      ]
    },
    "breath": {
      "pt": "Expira ao puxar, inspira ao voltar.",
      "en": "Breathe out as you pull, in as you return."
    }
  },
  "seatedrow": {
    "nPT": "Remada Sentada no Cabo",
    "nEN": "Seated Cable Row",
    "eq": {
      "pt": "Polia baixa + triângulo",
      "en": "Low pulley + V-handle"
    },
    "anim": "row",
    "pri": [
      "upperBack",
      "lats"
    ],
    "sec": [
      "biceps"
    ],
    "steps": {
      "pt": [
        "Sentado, pés apoiados, joelhos levemente fletidos.",
        "Coluna neutra, peito erguido.",
        "Puxa a pega ao abdómen, cotovelos junto ao corpo.",
        "Aperta as omoplatas no fim.",
        "Volta controlando sem arredondar as costas."
      ],
      "en": [
        "Seated, feet braced, knees slightly bent.",
        "Neutral spine, chest up.",
        "Pull the handle to your abdomen, elbows close to the body.",
        "Squeeze the shoulder blades at the end.",
        "Return under control without rounding the back."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Arredondar/balançar o tronco para trás.",
          "c": "Coluna neutra; o movimento vem dos braços e costas, não da lombar."
        },
        {
          "e": "Amplitude curta.",
          "c": "Estende bem à frente (sem arredondar) e puxa ao abdómen."
        }
      ],
      "en": [
        {
          "e": "Rounding/rocking the torso backwards.",
          "c": "Neutral spine; the movement comes from arms and back, not the lumbar."
        },
        {
          "e": "Short range of motion.",
          "c": "Reach well forward (without rounding) and pull to the abdomen."
        }
      ]
    },
    "safe": {
      "pt": [
        "Mantém a coluna neutra — não uses a lombar para puxar."
      ],
      "en": [
        "Keep a neutral spine — do not pull with your lower back."
      ]
    },
    "breath": {
      "pt": "Expira ao puxar, inspira ao voltar.",
      "en": "Breathe out as you pull, in as you return."
    }
  },
  "strarm": {
    "nPT": "Puxada com Braço Esticado",
    "nEN": "Straight-Arm Pulldown",
    "eq": {
      "pt": "Polia alta + barra",
      "en": "High pulley + bar"
    },
    "anim": "strarm",
    "pri": [
      "lats"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "De pé, ligeira inclinação à frente, polia no alto.",
        "Braços quase esticados, pega a barra.",
        "Puxa a barra para baixo até às coxas em arco.",
        "Foco em contrair o dorsal.",
        "Volta controlando com o dorsal."
      ],
      "en": [
        "Stand with a slight forward lean, pulley set high.",
        "Arms nearly straight, grip the bar.",
        "Sweep the bar down to your thighs in an arc.",
        "Focus on squeezing the lats.",
        "Return under control, resisting with the lats."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Fletir os cotovelos (vira pushdown).",
          "c": "Braços quase esticados durante todo o movimento."
        },
        {
          "e": "Usar o tronco para empurrar.",
          "c": "Tronco fixo; só os braços descem."
        }
      ],
      "en": [
        {
          "e": "Bending the elbows (it becomes a pushdown).",
          "c": "Arms stay nearly straight throughout."
        },
        {
          "e": "Using the torso to drive the bar.",
          "c": "Torso fixed; only the arms travel."
        }
      ]
    },
    "safe": {
      "pt": [
        "Isola o dorsal sem carregar a lombar."
      ],
      "en": [
        "Isolates the lats without loading the lower back."
      ]
    },
    "breath": {
      "pt": "Expira ao puxar, inspira ao voltar.",
      "en": "Breathe out as you pull, in as you return."
    }
  },
  "facepull": {
    "nPT": "Face Pull",
    "nEN": "Face Pull",
    "eq": {
      "pt": "Polia + corda",
      "en": "Cable + rope"
    },
    "anim": "reardelt",
    "pri": [
      "rearDelt"
    ],
    "sec": [
      "traps",
      "upperBack"
    ],
    "steps": {
      "pt": [
        "Corda na polia à altura do rosto.",
        "Pega com polegares para trás.",
        "Puxa a corda à testa, abrindo as mãos.",
        "Cotovelos altos; aperta a parte de trás dos ombros.",
        "Volta controlando."
      ],
      "en": [
        "Rope set at face height.",
        "Grip with thumbs pointing back.",
        "Pull the rope to your forehead, spreading your hands.",
        "Elbows high; squeeze the rear delts.",
        "Return under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Puxar demasiado baixo (vira remada).",
          "c": "Puxa à altura do rosto, cotovelos altos."
        },
        {
          "e": "Peso a mais, forma perdida.",
          "c": "Carga leve, qualidade acima de tudo."
        }
      ],
      "en": [
        {
          "e": "Pulling too low (it becomes a row).",
          "c": "Pull to face height, elbows high."
        },
        {
          "e": "Too heavy, form falls apart.",
          "c": "Light load, quality above all."
        }
      ]
    },
    "safe": {
      "pt": [
        "Excelente para saúde do ombro e postura."
      ],
      "en": [
        "Excellent for shoulder health and posture."
      ]
    },
    "breath": {
      "pt": "Expira ao puxar, inspira ao voltar.",
      "en": "Breathe out as you pull, in as you return."
    }
  },
  "hipthrust": {
    "nPT": "Elevação Pélvica",
    "nEN": "Hip Thrust",
    "eq": {
      "pt": "Máquina de Glúteo / Barra",
      "en": "Glute machine / barbell"
    },
    "anim": "hipthrust",
    "pri": [
      "glutes"
    ],
    "sec": [
      "hamstrings",
      "quads"
    ],
    "steps": {
      "pt": [
        "Costas apoiadas na almofada, carga sobre a bacia.",
        "Pés à largura dos ombros, calcanhares firmes.",
        "Estende a bacia para cima contraindo os glúteos.",
        "Topo: corpo em linha, sem hiperestender a lombar.",
        "Desce controlando."
      ],
      "en": [
        "Upper back on the pad, load across the hips.",
        "Feet shoulder-width, heels planted.",
        "Drive the hips up, squeezing the glutes.",
        "At the top: body in line, no lumbar hyperextension.",
        "Lower under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Hiperestender a lombar no topo.",
          "c": "Costelas para baixo; a extensão vem da bacia, não das costas."
        },
        {
          "e": "Empurrar com os dedos dos pés.",
          "c": "Empurra pelos calcanhares."
        }
      ],
      "en": [
        {
          "e": "Hyperextending the lower back at the top.",
          "c": "Ribs down; the extension comes from the hips, not the spine."
        },
        {
          "e": "Pushing through the toes.",
          "c": "Drive through the heels."
        }
      ]
    },
    "safe": {
      "pt": [
        "O movimento vem da bacia — protege as costas."
      ],
      "en": [
        "The movement comes from the hips — that protects your back."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you drive up, in as you lower."
    }
  },
  "dbrdl": {
    "nPT": "Levantamento Terra Romeno c/ Halteres",
    "nEN": "Dumbbell RDL",
    "eq": {
      "pt": "Halteres",
      "en": "Dumbbells"
    },
    "anim": "hinge",
    "pri": [
      "hamstrings",
      "glutes"
    ],
    "sec": [
      "lowerBack",
      "forearm"
    ],
    "steps": {
      "pt": [
        "Em pé, halteres à frente das coxas, joelhos levemente fletidos.",
        "Coluna neutra, peito erguido, escápulas encaixadas.",
        "Empurra a bacia atrás descendo os halteres junto às pernas.",
        "Desce até sentir alongar os posteriores (não mais).",
        "Volta empurrando a bacia à frente, apertando os glúteos."
      ],
      "en": [
        "Stand with the dumbbells in front of your thighs, knees slightly bent.",
        "Neutral spine, chest up, shoulder blades set.",
        "Push the hips back, sliding the dumbbells down along your legs.",
        "Lower until you feel the hamstrings stretch — no further.",
        "Come up by driving the hips forward, squeezing the glutes."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Arredondar a lombar (erro mais perigoso).",
          "c": "Coluna neutra sempre; pára antes de arredondar."
        },
        {
          "e": "Transformar em agachamento (joelhos à frente).",
          "c": "É uma dobradiça de anca: bacia atrás, joelhos quase fixos."
        }
      ],
      "en": [
        {
          "e": "Rounding the lower back (the most dangerous mistake).",
          "c": "Neutral spine always; stop before it rounds."
        },
        {
          "e": "Turning it into a squat (knees travelling forward).",
          "c": "It is a hip hinge: hips back, knees almost fixed."
        }
      ]
    },
    "safe": {
      "pt": [
        "CUIDADO COSTAS: carga leve, sobe devagar. RPE máx. 8. Se a lombar reclamar, troca por Mesa Flexora."
      ],
      "en": [
        "BACK CAUTION: light load, build up slowly. RPE 8 max. If your lower back complains, swap it for the Leg Curl."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao subir.",
      "en": "Breathe in as you lower, out as you come up."
    }
  },
  "legcurl_seat": {
    "nPT": "Mesa Flexora (sentado)",
    "nEN": "Seated Leg Curl",
    "eq": {
      "pt": "Máquina Flexora",
      "en": "Leg curl machine"
    },
    "anim": "legcurl",
    "pri": [
      "hamstrings"
    ],
    "sec": [
      "calves"
    ],
    "steps": {
      "pt": [
        "Ajusta o encosto e a almofada das coxas.",
        "Almofada inferior sobre o tendão de Aquiles.",
        "Flexiona os joelhos puxando os calcanhares para baixo/atrás.",
        "Segura no fim.",
        "Volta controlando."
      ],
      "en": [
        "Adjust the backrest and the thigh pad.",
        "Lower pad sitting over the Achilles tendon.",
        "Bend the knees, pulling the heels down and back.",
        "Hold at the end position.",
        "Return under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Bacia desliza para a frente.",
          "c": "Almofada das coxas firme; bacia fixa."
        },
        {
          "e": "Amplitude curta.",
          "c": "Flexão completa, controla a volta."
        }
      ],
      "en": [
        {
          "e": "Hips sliding forward.",
          "c": "Thigh pad snug; hips locked in place."
        },
        {
          "e": "Short range of motion.",
          "c": "Full flexion, control the return."
        }
      ]
    },
    "safe": {
      "pt": [
        "Bacia fixa protege a lombar."
      ],
      "en": [
        "Locked hips protect your lower back."
      ]
    },
    "breath": {
      "pt": "Expira ao flexionar, inspira ao voltar.",
      "en": "Breathe out as you curl, in as you return."
    }
  },
  "legcurl_l": {
    "nPT": "Mesa Flexora (deitado)",
    "nEN": "Lying Leg Curl",
    "eq": {
      "pt": "Máquina Flexora",
      "en": "Leg curl machine"
    },
    "anim": "legcurl",
    "pri": [
      "hamstrings"
    ],
    "sec": [
      "calves"
    ],
    "steps": {
      "pt": [
        "Deita de barriga para baixo, joelhos além da borda.",
        "Almofada acima do calcanhar.",
        "Bacia colada ao banco.",
        "Flexiona puxando os calcanhares aos glúteos.",
        "Desce controlando."
      ],
      "en": [
        "Lie face down with the knees just past the edge.",
        "Pad just above the heels.",
        "Hips pressed into the bench.",
        "Curl the heels toward the glutes.",
        "Lower under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Levantar a bacia (arqueia a lombar).",
          "c": "Bacia sempre no banco."
        },
        {
          "e": "Impulso da bacia.",
          "c": "Movimento só do joelho."
        }
      ],
      "en": [
        {
          "e": "Lifting the hips (arching the lower back).",
          "c": "Hips stay down on the bench."
        },
        {
          "e": "Driving with the hips.",
          "c": "Movement comes from the knee only."
        }
      ]
    },
    "safe": {
      "pt": [
        "Bacia no banco evita tensão lombar."
      ],
      "en": [
        "Hips on the bench keeps tension off the lower back."
      ]
    },
    "breath": {
      "pt": "Expira ao flexionar, inspira ao voltar.",
      "en": "Breathe out as you curl, in as you return."
    }
  },
  "legpress_h": {
    "nPT": "Leg Press (pés altos)",
    "nEN": "Leg Press (high stance)",
    "eq": {
      "pt": "Leg Press 45°",
      "en": "45° Leg Press"
    },
    "anim": "legpress",
    "pri": [
      "glutes",
      "hamstrings"
    ],
    "sec": [
      "quads"
    ],
    "steps": {
      "pt": [
        "Configuração do leg press, pés altos na plataforma.",
        "Costas e bacia apoiadas.",
        "Desce controlando com joelho a ~90°.",
        "Empurra pelos calcanhares.",
        "Foco em glúteo e posterior."
      ],
      "en": [
        "Same leg press setup, feet high on the platform.",
        "Back and hips fully supported.",
        "Lower under control to about 90° of knee bend.",
        "Drive through the heels.",
        "Focus on glutes and hamstrings."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Tirar a lombar do encosto.",
          "c": "Reduz amplitude; lombar apoiada."
        },
        {
          "e": "Travar os joelhos no topo.",
          "c": "Pára antes da extensão total."
        }
      ],
      "en": [
        {
          "e": "Lower back lifting off the pad.",
          "c": "Cut the range; keep the back supported."
        },
        {
          "e": "Locking the knees at the top.",
          "c": "Stop short of full extension."
        }
      ]
    },
    "safe": {
      "pt": [
        "Empurra pelos calcanhares; lombar apoiada."
      ],
      "en": [
        "Drive through the heels; keep the lower back supported."
      ]
    },
    "breath": {
      "pt": "Inspira ao descer, expira ao empurrar.",
      "en": "Breathe in as you lower, out as you press."
    }
  },
  "calf_seat": {
    "nPT": "Elevação de Panturrilha Sentado",
    "nEN": "Seated Calf Raise",
    "eq": {
      "pt": "Máquina de Panturrilha",
      "en": "Calf raise machine"
    },
    "anim": "calf",
    "pri": [
      "calves"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "Sentado, joelhos sob as almofadas, pontas dos pés na plataforma.",
        "Desce os calcanhares abaixo da linha (alongar).",
        "Sobe na ponta dos pés o máximo.",
        "Segura no topo.",
        "Desce devagar."
      ],
      "en": [
        "Seated, knees under the pads, balls of the feet on the platform.",
        "Let the heels drop below the platform (stretch).",
        "Rise onto the toes as high as possible.",
        "Hold at the top.",
        "Lower slowly."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Amplitude curta.",
          "c": "Alonga bem em baixo, contrai no topo."
        },
        {
          "e": "Ressaltar.",
          "c": "Controla a fase de alongamento."
        }
      ],
      "en": [
        {
          "e": "Short range of motion.",
          "c": "Full stretch at the bottom, squeeze at the top."
        },
        {
          "e": "Bouncing.",
          "c": "Control the stretch phase."
        }
      ]
    },
    "safe": {
      "pt": [
        "Controla o alongamento."
      ],
      "en": [
        "Control the stretch."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you rise, in as you lower."
    }
  },
  "pallof": {
    "nPT": "Pallof Press",
    "nEN": "Pallof Press",
    "eq": {
      "pt": "Polia + pega",
      "en": "Cable + handle"
    },
    "anim": "pallof",
    "pri": [
      "obliques",
      "abs"
    ],
    "sec": [],
    "steps": {
      "pt": [
        "De lado para a polia (altura do peito), pega com as duas mãos.",
        "Afasta-te para criar tensão.",
        "Empurra a pega à frente resistindo à rotação.",
        "Segura 2s.",
        "Volta ao peito. Faz os dois lados."
      ],
      "en": [
        "Stand side-on to the pulley (chest height), grip with both hands.",
        "Step away to create tension.",
        "Press the handle straight out, resisting the rotation.",
        "Hold for 2s.",
        "Bring it back to the chest. Do both sides."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Deixar o tronco rodar para a polia.",
          "c": "Resiste à rotação; core firme."
        },
        {
          "e": "Braços a fazer o trabalho.",
          "c": "A tensão está no core, não nos braços."
        }
      ],
      "en": [
        {
          "e": "Letting the torso rotate toward the pulley.",
          "c": "Resist the rotation; brace the core."
        },
        {
          "e": "Letting the arms do the work.",
          "c": "The tension belongs in the core, not the arms."
        }
      ]
    },
    "safe": {
      "pt": [
        "Anti-rotação — excelente para estabilizar a coluna."
      ],
      "en": [
        "Anti-rotation — excellent for spinal stability."
      ]
    },
    "breath": {
      "pt": "Expira ao empurrar, respira normal na retenção.",
      "en": "Breathe out as you press, breathe normally during the hold."
    }
  },
  "legraise": {
    "nPT": "Elevação de Pernas Suspenso",
    "nEN": "Hanging Leg Raise",
    "eq": {
      "pt": "Barra fixa",
      "en": "Pull-up bar"
    },
    "anim": "legraise",
    "pri": [
      "abs"
    ],
    "sec": [
      "obliques"
    ],
    "steps": {
      "pt": [
        "Suspenso na barra, corpo estável.",
        "Sem balançar, contrai o abdómen.",
        "Eleva os joelhos (ou pernas) até acima da bacia.",
        "Enrola a bacia no topo.",
        "Desce controlando sem baloiçar."
      ],
      "en": [
        "Hang from the bar, body steady.",
        "No swinging — brace the abs.",
        "Raise the knees (or legs) above hip level.",
        "Curl the pelvis at the top.",
        "Lower under control without swinging."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Baloiçar o corpo para subir.",
          "c": "Sem impulso; movimento controlado do abdómen."
        },
        {
          "e": "Só levantar as pernas sem enrolar a bacia.",
          "c": "Enrola a bacia para trabalhar mesmo o abdómen."
        }
      ],
      "en": [
        {
          "e": "Swinging the body to get the legs up.",
          "c": "No momentum; controlled movement from the abs."
        },
        {
          "e": "Only lifting the legs without curling the pelvis.",
          "c": "Curl the pelvis to actually work the abs."
        }
      ]
    },
    "safe": {
      "pt": [
        "Se for difícil, começa com joelhos fletidos."
      ],
      "en": [
        "If it is too hard, start with bent knees."
      ]
    },
    "breath": {
      "pt": "Expira ao subir, inspira ao descer.",
      "en": "Breathe out as you raise, in as you lower."
    }
  },
  "cablecrunch": {
    "nPT": "Abdominal na Polia",
    "nEN": "Cable Crunch",
    "eq": {
      "pt": "Polia alta + corda",
      "en": "High pulley + rope"
    },
    "anim": "cablecrunch",
    "pri": [
      "abs"
    ],
    "sec": [
      "obliques"
    ],
    "steps": {
      "pt": [
        "De joelhos de frente para a polia alta, corda atrás da cabeça.",
        "Bacia fixa, ancas imóveis.",
        "Enrola a coluna trazendo as costelas à bacia.",
        "Contrai o abdómen no fim.",
        "Volta controlando."
      ],
      "en": [
        "Kneel facing the high pulley, rope behind your head.",
        "Hips locked, no movement at the hip joint.",
        "Curl the spine, bringing the ribs toward the pelvis.",
        "Squeeze the abs at the end.",
        "Return under control."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Puxar com os braços/anca (vira agachamento).",
          "c": "Anca fixa; enrola a coluna com o abdómen."
        },
        {
          "e": "Amplitude curta.",
          "c": "Enrola bem, aproxima o peito da bacia."
        }
      ],
      "en": [
        {
          "e": "Pulling with the arms/hips (it becomes a squat).",
          "c": "Hips fixed; curl the spine with the abs."
        },
        {
          "e": "Short range of motion.",
          "c": "Curl fully, bringing the chest toward the pelvis."
        }
      ]
    },
    "safe": {
      "pt": [
        "O movimento é enrolar a coluna, não dobrar a anca."
      ],
      "en": [
        "The movement is a spinal curl, not a hip bend."
      ]
    },
    "breath": {
      "pt": "Expira ao enrolar, inspira ao voltar.",
      "en": "Breathe out as you crunch, in as you return."
    }
  },
  "birddog": {
    "nPT": "Bird-dog",
    "nEN": "Bird-dog",
    "eq": {
      "pt": "Peso corporal",
      "en": "Bodyweight"
    },
    "anim": "birddog",
    "pri": [
      "lowerBack",
      "glutes"
    ],
    "sec": [
      "abs"
    ],
    "steps": {
      "pt": [
        "Quatro apoios: mãos sob ombros, joelhos sob a bacia.",
        "Core firme, coluna neutra.",
        "Estende braço direito e perna esquerda.",
        "Segura 2s, bacia estável.",
        "Volta e alterna."
      ],
      "en": [
        "On all fours: hands under shoulders, knees under hips.",
        "Core braced, neutral spine.",
        "Extend the right arm and left leg.",
        "Hold for 2s, hips steady.",
        "Return and alternate."
      ]
    },
    "errs": {
      "pt": [
        {
          "e": "Rodar a bacia ao estender.",
          "c": "Bacia estável, como um copo de água nas costas."
        },
        {
          "e": "Arquear a lombar.",
          "c": "Coluna neutra do início ao fim."
        }
      ],
      "en": [
        {
          "e": "Hips rotating as you extend.",
          "c": "Keep the hips level, as if balancing a glass of water on your back."
        },
        {
          "e": "Arching the lower back.",
          "c": "Neutral spine start to finish."
        }
      ]
    },
    "safe": {
      "pt": [
        "Excelente estabilidade lombar — reforça o que te protege sentado."
      ],
      "en": [
        "Great lumbar stability — it reinforces what protects you while sitting."
      ]
    },
    "breath": {
      "pt": "Expira ao estender, inspira ao recolher.",
      "en": "Breathe out as you extend, in as you return."
    }
  }
};

export type ExerciseKey = keyof typeof EXERCISES;
