/**
 * GENERATED by scripts/port-content.mjs from old/js/data.js. Do not edit by hand.
 *
 * This is the authored training programme, ported verbatim. The source file's own
 * header says it plainly: do not "improve" these. Rep ranges, loads, RPE targets and
 * every line of bilingual technique text are the user's training plan, not copy.
 */

import type { Bilingual } from './schema';

export const MUSCLES: Readonly<Record<string, Bilingual>> = {
  "chest": {
    "pt": "Peitoral",
    "en": "Chest"
  },
  "frontDelt": {
    "pt": "Deltoide ant.",
    "en": "Front delt"
  },
  "sideDelt": {
    "pt": "Deltoide lat.",
    "en": "Side delt"
  },
  "rearDelt": {
    "pt": "Deltoide post.",
    "en": "Rear delt"
  },
  "biceps": {
    "pt": "Bíceps",
    "en": "Biceps"
  },
  "triceps": {
    "pt": "Tríceps",
    "en": "Triceps"
  },
  "forearm": {
    "pt": "Antebraço",
    "en": "Forearm"
  },
  "abs": {
    "pt": "Abdómen",
    "en": "Abs"
  },
  "obliques": {
    "pt": "Oblíquos",
    "en": "Obliques"
  },
  "lats": {
    "pt": "Dorsal",
    "en": "Lats"
  },
  "upperBack": {
    "pt": "Costas sup.",
    "en": "Upper back"
  },
  "traps": {
    "pt": "Trapézio",
    "en": "Traps"
  },
  "lowerBack": {
    "pt": "Lombar",
    "en": "Lower back"
  },
  "glutes": {
    "pt": "Glúteo",
    "en": "Glutes"
  },
  "quads": {
    "pt": "Quadríceps",
    "en": "Quads"
  },
  "hamstrings": {
    "pt": "Posteriores",
    "en": "Hamstrings"
  },
  "calves": {
    "pt": "Panturrilha",
    "en": "Calves"
  }
};

export type MuscleKey = keyof typeof MUSCLES;
