/**
 * Os músculos, nas quatro línguas.
 *
 * O cabeçalho deste ficheiro dizia "GENERATED by scripts/port-content.mjs" e isso
 * deixou de ser verdade a 2026-09-21: `old/` não é fonte de nada e `npm run port:content`
 * não é o caminho do conteúdo. Não se corre por cima deste ficheiro.
 *
 * As quatro línguas entraram no Passo F, 2026-09-22. Estes nomes são etiquetas curtas
 * de cartão e de tira — "Deltoide ant.", não "Deltoide anterior". A abreviatura é
 * medida: o rótulo vive num chip estreito. Cada língua abrevia à sua maneira e é por
 * isso que não se traduz palavra a palavra do português.
 */

import type { Localized } from './schema';

export const MUSCLES: Readonly<Record<string, Localized>> = {
  "chest": {
    "pt": "Peitoral",
    "en": "Chest",
    "es": "Pectoral",
    "fr": "Pectoraux"
  },
  "frontDelt": {
    "pt": "Deltoide ant.",
    "en": "Front delt",
    "es": "Deltoides ant.",
    "fr": "Deltoïde ant."
  },
  "sideDelt": {
    "pt": "Deltoide lat.",
    "en": "Side delt",
    "es": "Deltoides lat.",
    "fr": "Deltoïde lat."
  },
  "rearDelt": {
    "pt": "Deltoide post.",
    "en": "Rear delt",
    "es": "Deltoides post.",
    "fr": "Deltoïde post."
  },
  "biceps": {
    "pt": "Bíceps",
    "en": "Biceps",
    "es": "Bíceps",
    "fr": "Biceps"
  },
  "triceps": {
    "pt": "Tríceps",
    "en": "Triceps",
    "es": "Tríceps",
    "fr": "Triceps"
  },
  "forearm": {
    "pt": "Antebraço",
    "en": "Forearm",
    "es": "Antebrazo",
    "fr": "Avant-bras"
  },
  "abs": {
    "pt": "Abdómen",
    "en": "Abs",
    "es": "Abdomen",
    "fr": "Abdos"
  },
  "obliques": {
    "pt": "Oblíquos",
    "en": "Obliques",
    "es": "Oblicuos",
    "fr": "Obliques"
  },
  "lats": {
    "pt": "Dorsal",
    "en": "Lats",
    "es": "Dorsal",
    "fr": "Grand dorsal"
  },
  "upperBack": {
    "pt": "Costas sup.",
    "en": "Upper back",
    "es": "Espalda sup.",
    "fr": "Haut du dos"
  },
  "traps": {
    "pt": "Trapézio",
    "en": "Traps",
    "es": "Trapecio",
    "fr": "Trapèzes"
  },
  "lowerBack": {
    "pt": "Lombar",
    "en": "Lower back",
    "es": "Lumbar",
    "fr": "Lombaires"
  },
  "glutes": {
    "pt": "Glúteo",
    "en": "Glutes",
    "es": "Glúteo",
    "fr": "Fessiers"
  },
  "quads": {
    "pt": "Quadríceps",
    "en": "Quads",
    "es": "Cuádriceps",
    "fr": "Quadriceps"
  },
  "hamstrings": {
    "pt": "Posteriores",
    "en": "Hamstrings",
    "es": "Isquiotibiales",
    "fr": "Ischio-jambiers"
  },
  "calves": {
    "pt": "Panturrilha",
    "en": "Calves",
    "es": "Gemelos",
    "fr": "Mollets"
  }
};

export type MuscleKey = keyof typeof MUSCLES;
