/**
 * GENERATED by scripts/port-content.mjs from old/js/data.js. Do not edit by hand.
 *
 * This is the authored training programme, ported verbatim. The source file's own
 * header says it plainly: do not "improve" these. Rep ranges, loads, RPE targets and
 * every line of bilingual technique text are the user's training plan, not copy.
 */

/**
 * Every id was checked through the YouTube oEmbed endpoint in the previous
 * implementation. The player is a facade: a local poster image, an iframe created
 * only on tap, `enablejsapi` deliberately omitted, and no outbound link anywhere.
 */
export const VIDEOS: Readonly<Record<string, string>> = {
  "legpress": "waAxlYvtCcI",
  "hack": "Whp712OHPl8",
  "legext": "Svq2T3L9oKo",
  "lunge": "mKRq_p3hQr4",
  "calf_s": "SorIB5_zO9A",
  "plank": "9dn5Fb3cSoE",
  "dbbench": "tDxKGeY-hjQ",
  "incldb": "G-i3jMIbDmo",
  "pecdeck": "FwtqdGlRgig",
  "pushdown": "M-DTY40JG9M",
  "ohext": "fpKepisjHWk",
  "skull": "5yqU0BnErZc",
  "dbohp": "0uB7PH3oFVo",
  "lateral": "jannLx4RxKo",
  "reardelt": "EWwR2Z-yHjQ",
  "dbcurl": "k31LK_VASok",
  "hammer": "xvvjkh3Aa4s",
  "cablecurl": "zqklqTcOsbo",
  "pulldown": "S3HYdarCHDo",
  "csrow": "VvT8ZFAo21Y",
  "seatedrow": "2YebbYuuBJQ",
  "strarm": "7XprSYwflfw",
  "facepull": "YxQivR_kljk",
  "hipthrust": "OCMjir2i6uU",
  "dbrdl": "tveTE065Ub0",
  "calf_seat": "qpVKOlniMXo",
  "pallof": "91zJZhRx2u0",
  "legraise": "-FQn23icsoY",
  "cablecrunch": "I64bjVbs7XI",
  "cgbench": "cXbSJHtjrQQ",
  "dip": "J3WYrjNDLI4",
  "kickback": "ZvF4Oi_6Vtg",
  "legcurl_seat": "sWSm1pWb3lw",
  "legcurl_l": "AugHEfM7rdM",
  "legpress_h": "wEVyxxek1d0",
  "birddog": "5oNxXM4cfiU",
  "treadmill": "raa5u4CF2Q4",
  "bike": "qwTBKqiCGpM"
};
